src/components/Button/Button.tsx, src/components/IconButton/IconButton.stories.mdx, src/components/IconButton/IconButton.style.ts, src/components/IconButton/IconButton.tsx, src/components/IconButton/index.ts
This PR implements the icon button component. 
This component will just implement the icon component of the library inside the button component.
We do this to skip over-engineer stuff to implement one icon that is clickable in any project, also serves well for the upcoming pagination component.
=> new icon button implementation

package.json
This PR change the npm hook for install.
The issue was that when no node modules where installed the install hook failed to run build. So i changed it to run after the installation
=> fix build for production

src/components/Label/Label.style.ts
The notorious zindex on the label that had nothing to do with the component
=> fix zindex on labels

.storybook/preview.js, src/components/Button/Button.style.ts, src/components/CheckBox/CheckBox.style.ts, src/components/ThemeProvider/ThemeProvider.tsx, src/globals.d.ts, src/theme/palette.ts, src/utils/themeFunctions.ts
This PR fix the function that deep merge the theme with the new theme passed to the provider. This was overlapping the object assigned but now it only extends it.
I also fixed the naming of the `brand1`, `brand2` to `branded` as we used both cases.
=> Fix merge technique of theming

src/components/Select/Select.tsx
This PR extends the support of select option value for both string and number as there is no point to limit it to just `string`, values can be anything
=> Extend Select TS support

src/components/Table/Table.tsx
Make sure the selecting ids are being re-initialized when the data are changed. This is because we might not have an id anymore that was selected before
=> reset table ids when data is changed

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/TableRowContext.ts, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
In this PR we introduce a new option on the table data to define the width percentage of the cell. This is applied to all the columns and leave the columns with no width defined to the window to calculate their size. 
_Only downfall to this solution is if you define more than 100% width to your columns._
=> add percentage width option

src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
This PR wraps the content of the inline header table cell to a span in order for the QA to be able to "catch" the contents with selenium and xPath
=> wrap inline header content to span

src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.style.ts, src/components/DatePicker/DatePicker.tsx
This PR introduce to the datepicker 2 new properties
* disableDates
* value
There would be always a case that we will need to disable some dates in the calendar in order to avoid user clicking on them. This is very common and also there is a need for it in a current task in Video hunter.
Also value is also need if someone want to control the value with an external state.
You can also find two new stories that shows both cases.
disabled dates
value defined in the component
=> fix: datepicker with value and disabledDates from outside

src/components/DatePicker/DatePicker.tsx
This PR is a hot fix solving an issue that when `onChange` and `value` prop where defined and you were trying to handle the component from parent there was a infinite loop on the component rendering causing trouble.
Now as you can see we detect external `value` changes and handle them internally in order to handle both `stateless` and `statefull` cases.
A new function also created to merge and simplify functionality of range and day pick
=> fix: datepicker on change combined with value was not working properly

.storybook/main.js, src/components/Label/Label.style.ts, src/components/Label/Label.tsx, src/components/TextField/TextField.stories.mdx, src/components/TextField/TextField.style.ts, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/storyUtils/TextFieldShowcase/TextFieldShowcase.tsx, src/components/storyUtils/TextFieldShowcase/index.ts, src/utils/themeFunctions.ts, yarn.lock
This PR includes the Error Handling enhancements of TextField component.
[Abstract Designs](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/e8803d0d-0c59-4eeb-9d4e-1cae0df12a08/commits/latest/files/d7b356b2-3f84-47de-8d32-8b811b5c4590/layers/0C8A2CB3-97AA-4191-8D8E-8865D27A6C4F?collectionId=ed3a1a60-78e2-4d01-a8bd-fd4e8d6356cd&collectionLayerId=4b90e2b3-7e5d-400a-94fb-d6595af34221)
Closes issue #73 
**Updates and Changes**
* Addition of error/success indicators
* Addition of error message
* Update of label color on error state
* Update of error handling story
=> [TextField] Error Handling  Implementation

src/components/TextField/TextField.style.ts
This PR fixes the width of TextField that is now not fully expanded into its parent container.
Behaviour before fix:
Behaviour after fix:
=> [TextField] Fix width to fit the parent container

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.tsx
This PR extends the functionality of the Datepicker and adds a new prop to handle a custom label for the input/inputs.
This way we can add anything we want as we do on the `TextField` component. The prop is optional and defaults to the label of the design `Date`
I also extended the knobs functionality so we can play with these values
=> introduce custom label to datepicker

src/components/TextField/TextField.stories.mdx, src/components/TextField/TextField.style.ts, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/storyUtils/TextFieldShowcase/TextFieldShowcase.tsx, src/theme/palette.ts, yarn.lock
This PR introduces the following:
**1.** New styles of the TextField component:
- Filled
- Outlined
- Elevated
**2.** Some minor fixes on the existing default style (filled).
The fixes applied are the following:
- Replacement of border with box-shadow inset (for avoiding resizing of component on state change)
- Fix styling of label when the input value is empty (should have font-weight normal)
- Fix styling of error state (should have a light red background)
- Fix disabled state (should have a white layer with opacity)
**3.** Addition of focus state for all components
_Note 1: All existing stories have been updated to show all the available styles along with the lean option._
_Note 2: Minor fixes to the colors have been made to match the designs._
Closes issue #78 
Designs on Abstract: …
=> [TextField] Add new styles and focus state

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.tsx
This PR introduce the new style types (elevated, filled, outlined) to the datepicker component. I also included some knobs functionality on the stories of the day and datepicker for the viewer to handle it and demonstrate it
closes #87 
Storyshots are the same
=> feat: adding style type selections to datepicker

guides/COLORS.stories.mdx, src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/components/DatePicker/DatePicker.style.ts, src/components/Icon/__snapshots__/Icon.stories.storyshot, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Menu/Menu.style.ts, src/components/Menu/Menu.tsx, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/TableCell/TableCell.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/theme/palette.ts, src/theme/utils.ts
In previous version we had complicated and contradicting way of creating the colors. 
In this PR there is only one rule for creating all the colors.
Each color includes seven shades, the base color (color400) and six shades deriving from color400,
three darker and three lighter.
All new shades are calculated with color percentages (25%, 50%, 75%) on white background for the lighter shades and black background for the darker ones (75%, 50%, 25%).
No screenshot on this.
Storyshots tests are updated based on the css objects returned.
=> feat(palette): Update palette color creation

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePickInput/__tests__/DatePickInput.js, src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.tsx, src/components/ThemeProvider/ThemeProvider.tsx, src/utils/helpers.ts, src/utils/initLocaleFormat.ts
This PR adds the ability to the user to change the date format of the date picker based on the list of localized formats in [dayjs](https://day.js.org/docs/en/display/format).
**Example of a new date format:**
**List of localized formats:**
resolves #100
=> feat(datepicker): adds date format option for date pick input

src/components/Button/__snapshots__/Button.stories.storyshot, src/components/Icon/__snapshots__/Icon.stories.storyshot, src/theme/palette.ts
BREAKING CHANGE: A new blue was added. Default info color changed to darkBlue
In this PR:
- A new color was added. There was the need for a new blue color that is in between the existing darkBlue and blue. So now we have darkBlue , blue and lightBlue.
- The default info color was changed from blue to darkBlue. 
The changes will break the UI colors. In order to keep everything the same, wherever blue is used it must be changed to lightBlue and the info color must be set through the ThemeProvider to lightBlue.  
new palette blues:
new info color:
Snapshots updated.
=> feat: add new blue color and info is set to darkBlue

src/components/Radio/Radio.stories.mdx, src/components/Radio/Radio.style.ts, src/components/Radio/Radio.tsx, src/components/Radio/__snapshots__/Radio.stories.storyshot, src/components/RadioGroup/__snapshots__/RadioGroup.stories.storyshot, src/components/storyUtils/RadioButtonsShowcase/RadioButtonsShowcase.tsx
Add a new filled property for radio button and refactor it according to the new designs in [here](https://app.abstract.com/projects/96260c1d-f169-4306-ab88-2472d8e457fd/branches/master/commits/8ee49d1694bc21aa2be9b3c0c83cfb8c0103eb83/files/246e136b-c8fc-4641-a81d-8f110268eab8/layers/325C9C2B-C694-40CE-9059-6BB12287E461?mode=build&selected=3818514689-ED230193-2C29-4CF2-8448-2C867E6F3867&sha=8ee49d1694bc21aa2be9b3c0c83cfb8c0103eb83)
Issue solved: [here](https://github.com/Orfium/orfium-ictinus/issues/118)
resolves: #118 
In more details: 
- remove uneeded code (wrapperStyles had a hover style for inner spans but customRadioWrapperStyles had the same hover, so it was duplicated). 
- add an onMouseOver at Radio.tsx in order to update the focused state because it didnt use to work properly …
=> refactor(radio-button): refactor according the new designs and add filled property

src/components/CheckBox/CheckBox.stories.mdx, src/components/CheckBox/CheckBox.style.ts, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot
Add a new filled property for checkbox and refactor it according to the new designs in here
resolves: #119 
In more details:
* remove uneeded code 
* update hover's shadow color and width/height of checkbox and of parent element
* update shapes and theirs colors according to designs 
* add outline property
* create a new story with props
Before : 
Now: 
Update the snapshots
=> refactor(checkbox): refactor according the new designs and add outlined

src/components/CheckBox/CheckBox.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot
When the checkbox component is imported in another project the snapshots of the component that uses the checkbox will fail due to autogenerated id. 
I passed a new prop to give us the ability to pass a static id in our snapshot tests to avoid this issue in future usages.
=> fix(checkbox): adds a prop to disable autogenerated id for snapshots

src/components/Pagination/Pagination.stories.mdx, src/components/Pagination/Pagination.tsx
Using pagination with react query requires handling the next/prev buttons.
We should be able to navigate to the next page only when the fetched data are ready. 
That said, we need 2 additional properties to be able to disable the pagination buttons manually.
**Note:**  _this is for v1 as it does not affect the current functionality of the component_.
=> feat(pagination): adds two new props for disabling prev and next buttons

src/components/TextField/TextField.tsx
Conflicting 'size' props from TextField and HTMLInputProps caused a type error to be thrown when the prop was used. This fixes that.
=> fix(textfield): fixes size prop causing a typescript error

src/components/Chart/BarChart/utils.ts
Format tick number correctly when number is greater than billion
=> fix(barchart): add Billion case in tickformatter

package.json, yarn.lock
Webstorm's commit functionality was crashing due to incorrect peer dependencies.
=> fix: updates ts-jest dev dependency

src/components/Button/Button.stories.mdx, src/components/Button/Button.style.ts, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/Chart/BarChart/components/CustomTooltipContent/CustomTooltipContent.tsx, src/components/IconButton/IconButton.stories.mdx, src/components/IconButton/IconButton.style.ts, src/components/IconButton/IconButton.tsx, src/components/Modal/Modal.tsx, src/components/Modal/ModalContent/ModalContent.style.ts, src/components/Pagination/Pagination.tsx, src/components/Pagination/__snapshots__/Pagination.stories.storyshot
This PR introduce a new design addon for buttons which is the transparent state. This state actually is like the non-filled without the border.
Introduce feature is also applied to icon buttons.
This feature applied already to modal close button and pagination buttons which previously was using the filled version of it.
Updated snapshots
=> [DS-93][DS-95][DS-97] Feat/button transparent

src/components/AssetMatching/Assetmatching.tsx, src/components/AssetMatching/components/SectionHeader/SectionHeader.tsx, src/hooks/useCheck.ts
I forgot to expose the setChecked state handler of the checkbox.  🤭
This is a minor fix that passes the state handler to the onCheck callback.
=> fix: passes setChecked state handler as an argument in onCheck callback

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/AssetMatching/components/CheckBoxContainer/CheckBoxContainer.tsx, src/components/storyUtils/AssetMatchingShowcase/AssetMatchingShowcase.tsx, src/hooks/useCheck.ts
- adds a new button in a showcase for checking the component from a parent component.
- adds useEffect and passed isChecked to Checkbox component.
updates snapshot
=> fix: adds state update on isChecked param change 

src/components/AssetMatching/Assetmatching.tsx, src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/hooks/useCheck.ts
Removes proposed solution after the last PR and adds a key that changes dynamically to force rerender the component.
We can use a key that changes dynamically every time the parent components change the boolean prop `isChecked`. This way, we force the section component that contains the checkbox to rerender and pass down the updated value of `isChecked` prop without using the useEffect hook.
=> fix: removes proposed solution after last PR 

src/components/Drawer/Navigation/MenuItem/MenuItem.tsx, src/components/Drawer/types.ts
On initial render , the active classname is not appended.  This PR introduces the [isActive](https://reactrouter.com/web/api/NavLink/isactive-func) function as an optional param to help solve this issue. 
[Ticket](https://orfium.atlassian.net/browse/DS-125)
=> Feat/Optional isActive

src/components/AssetMatching/AssetMatching.stories.mdx, src/components/AssetMatching/Assetmatching.tsx, src/components/AssetMatching/components/CheckBoxContainer/CheckBoxContainer.tsx, src/components/AssetMatching/components/SectionHeader/SectionHeader.tsx, src/components/storyUtils/AssetMatchingShowcase/BulkActionsShowcase.tsx, src/components/storyUtils/AssetMatchingShowcase/SectionHeaderShowcase.tsx
- adds `isCheckboxEnabled` prop for explicitly handling checkbox `disabled` prop
- changes the behavior of default probability score element
- updates `SectionHeader` showcase.
=> fix(asset-matching): adds prop for explicitly handling checkbox

src/components/AssetMatching/components/ActionsToolbox/ActionsToolbox.tsx, src/components/AssetMatching/components/ActionsToolbox/ActionsToolboxWrapper.tsx, src/components/AssetMatching/components/ActionsToolbox/SecondaryActions.tsx, src/components/AssetMatching/components/SectionHeader/SectionHeader.style.ts, src/components/AssetMatching/components/SectionHeader/SectionHeader.test.tsx
Introduce new behavior for the matching asset header actions, plus new style when card is selected.
[DS-ticket](https://orfium.atlassian.net/browse/DS-111)
=> [DS-111]: header behavior 

src/components/Notification/Notification.style.ts
[DS-141]
The Notification component's background-color property defaults to `transparent`, when the `styleType` is `outlined`. This PR applies the `white` color to the `outlined` type, so that no overrides are needed in the clients that use it.
[DS-141]: https://orfium.atlassian.net/browse/DS-141
=> fix(notification): add background color [DS-141]

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx, src/components/Table/components/TableCell/TableCell.tsx, src/components/Table/components/TableRowWrapper/TableRowWrapper.tsx
In this PR test-ids for all `th` and `td` table elements are added:
- `th` : test-id based on the column name (e.g.  column name `First Name` -> `table_header_first_name`)
- `td` : generic test-id with 2d indexing (row and column, e.g. `table_row_4_cell_2` )
Also the user can enter an optional dataTestIdPrefix (e.g. `cmo_table_header_first_name` or `cmo_table_row_4_cell_2`)
=> feat(table): test ids

src/components/Notification/NotificationVisual/NotificationVisual.tsx, src/components/Notification/Snackbar/Snackbar.tsx
In this PR we change the buttons on Toast and Snackbar to have primary color ( the default ) and the secondary CTA to be transparent.
[ticket](https://orfium.atlassian.net/browse/DS-100)
[designs](https://www.figma.com/file/8kMPBNYHHXz2AtkzeeDmk5/Design-System?node-id=201%3A5004)
=> [DS-100] Feat / Notifications buttons style change

src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot
[DS-101](https://orfium.atlassian.net/browse/DS-101)
When the Select component is onFocus state the stroke style is not applied always. The stroke appears only if you click on the input field; if you click the downArrow icon the stroke is not applied. With this PR the stroke is applied in both cases (input field click or downArrow icon click)
=> fix(select): on focus stroke issue

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Label/Label.style.ts, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/TextArea.style.ts, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/TextField.style.ts, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/utils/TextInputWrapper/TextInputWrapper.style.ts
[DS-152]
Fixes issue where resizing a text field would result in the Label rendering in inconsistent positions, because of a percentage-based value. 
Issue: 
[DS-152]: https://orfium.atlassian.net/browse/DS-152
=> fix: fix label position in text elements [DS-152]

src/components/Button/Button.style.ts, src/components/Button/Button.tsx, src/components/ButtonBase/ButtonBase.style.ts, src/components/ButtonBase/ButtonBase.tsx, src/components/ButtonBase/index.ts, src/components/ButtonBase/utils.ts, src/components/IconButton/IconButton.style.ts, src/components/IconButton/IconButton.tsx, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/TextArea/TextArea.style.ts, src/components/TextArea/TextArea.tsx, src/components/TextField/TextField.tsx, src/components/TextInputBase/TextInputBase.style.ts, src/components/TextInputBase/TextInputBase.tsx, src/components/TextInputBase/index.ts
In this PR i tried to simplify how we use bases on the system. I introduce the `ButtonBase` in order to use a single responsibility component for both of our Button and IconButton. 
Furthermore i moved the TextWrapper and use it as TextInputBase in order to much the previous logic.
Those components are going to be without the usual readme file for storybook.
Secure all old snapshots are working without a problem
=> refactor: old text bases and introduce button base

src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/ExtendedColumnItem/ExtendedColumnItem.tsx, src/components/Table/components/TableCell/TableCell.style.tsx, src/components/Table/components/TableCell/TableCell.tsx
Design QA Fixes for Table. 
When sorting is applied, the respective column's text should have the 'active state' styles applied.
In the screenshot below, you can see the active state (first column), the normal state and the hover state (last column).
=> fix: design qa fixes for table

src/components/Table/Table.tsx, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
[DS-216]
The function that determines whether a column only contains numerical values has a bug that needs fixing, because strings like '17 Feb 2020' are evaluated as numbers.
[DS-216]: https://orfium.atlassian.net/browse/DS-216
=> fix: fix columnHasNumberArr evaluation function

src/components/Filter/Filter.stories.mdx, src/components/Filter/Filter.style.ts, src/components/Filter/__snapshots__/Filter.stories.storyshot
[DS-240](https://orfium.atlassian.net/browse/DS-240)
+ If content's width is < = to filter's top, both top and menu have the same width
+ Menu's min width is 150 (same with min width of the top)
+ Menu's max width is 620 (same with min width of the top)
=> fix: [DS-240] truncated content to Filter menu

src/components/Filter/Filter.style.ts, src/components/Filter/__snapshots__/Filter.stories.storyshot, src/components/Filter/utils.ts
[DS-237](https://orfium.atlassian.net/browse/DS-237)
Changed for `hover` state so as background color  to be 10% darken (or lighten) of the `default` color
=> fix: [DS-237] change hover bg-color to filter

src/components/Drawer/Navigation/MenuItem/MenuItem.tsx
Icon color on non expandable items should be the same as on expandable items.
Ticket: https://orfium.atlassian.net/browse/DS-266
=> [DS-266]: Fix/navigation parent item icon color

src/components/Button/__snapshots__/Button.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/hooks/useTypeColorToColorMatch.tsx
Remember all those times that the text returned black when it should have been white? All those times `primary` didn't work? Well, `#8c0d95 === #8C0D95` returns false :) *screams internally*
=> fix: adds toLowerCase in string equality

src/components/Filter/Filter.style.ts, src/components/Filter/Filter.tsx, src/components/Filter/types.ts, src/components/Filter/utils.ts
- Fix Filter color calculations by deprecating the `activeCalculatedColor` variable and only using the generated palette that is provided by the user through the `theme` prop (`calculatedColor`)
Before (secondary: `blue-600`): 
After (secondary: `blue-600`):
=> fix: fix color calculations

src/components/Filter/Filter.style.ts
- Fixes issue where filters would not take up the full min-width space when they were smaller than 150px
Before: 
After: 
**PS: ~We can also completely remove the `min-width` rule. Please advise. This proposal accommodates the min-width rule.~ The designs show an updated `min-width` of `110px`.**
=> fix: make filters take up full width when min-width is triggered

.releaserc
This PR adds `style` word to the semantic release to trigger patch release. Now it skips it like `chore`
=> chore: update ci for style to create patch release

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Filter/Filter.style.ts, src/components/Filter/Filter.tsx, src/components/Filter/components/FilterBase/FilterBase.tsx
[DS-317]
- Resizes icons inside filter between types (arrowUp, calendar)
- Adds color swatch functionality to icons
- Adds whitespace after ':' in label
After:
[DS-317]: https://orfium.atlassian.net/browse/DS-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add color swatch and resize icons in filter

src/components/Avatar/Avatar.style.ts, src/components/Avatar/Avatar.tsx, src/components/ButtonBase/ButtonBase.style.ts, src/components/CheckBox/CheckBox.tsx, src/components/Chip/components/Badge/Badge.style.ts, src/components/DatePicker/Day/Day.style.ts, src/components/Drawer/Navigation/MenuItem/MenuItem.tsx, src/components/Filter/utils.ts, src/components/IconButton/IconButton.tsx, src/components/Menu/Menu.tsx, src/components/Tooltip/Tooltip.style.ts, src/components/storyUtils/ColorUtility/ColorUtility.tsx, src/components/storyUtils/PaletteShowcase/PaletteShowcase.style.tsx, src/components/storyUtils/PaletteShowcase/PaletteShowcase.tsx, src/theme/index.ts, src/theme/palette.ts, src/theme/tests/utils.test.ts, src/theme/types.ts
I started this an an investigation to check out if it's  doable. It turns out that it's feasible so I made it a PR.
I wanted to remove the `enhancePaletteWithShades` from the `pickTextColorFromSwatches` function since it's a recursive function and it's not something we have to run each and every time we need to have a AA text.
I also moved the getColor function to the palette since it's a palette function.
Finally, I renamed the `pickTextColorFromSwatches` to `getAAColorFromSwatches` and the `getAATextColor` to `getAAColor` and added them to theme.utils.
Tested the getAAColor individually. No futher tests needed as it was more of a performance gain and no visual changes where made.
=> [NO-JIRA] Refactor / palette functions

src/components/CheckBox/CheckBox.style.ts, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot
The checkbox input element is absolutely positioned within a span without an explicit position value. This causes issues when there are other positioned ancestors higher up in the DOM tree.
=> [DS-347] fix/Checkbox positioning bug

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.style.ts, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap
- Re-adding the `width: 100%` property since it was removed in a previous version and all components that used TextInputBase are probably broken.
=> fix: add 100% width in input styles

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.style.ts, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap
- Removes a `flex: 1 1 100%` rule that caused the text components to break their width/height constraints when in a flex container
=> fix: remove css rule that broke text components when in a flex container

docs/system/THEME.stories.mdx, src/components/ThemeProvider/ThemeProvider.tsx, src/theme/index.ts, src/theme/palette.ts, src/theme/types.ts
depends on https://github.com/Orfium/orfium-ictinus/pull/479
*This PR will be a part of 3 that has a goal for a small fix that I made for dark mode first try. 2/3*
In this PR I am adding the switch dark mode functionality inside the `ThemeProvider` in order to switch from `light` to `dark`. 
No screenshot applied
=> feat: fix dark mode switch and deprecate old isDark 2/3

src/components/Filter/Filter.style.ts
[DS-363](https://orfium.atlassian.net/browse/DS-363)
The issue was resolved by increasing the z-index value of the Filter Menu (value same as in Select Menu)
=> [DS-363]: fix: Select and Filter overlap issue 

src/components/Modal/Modal.style.ts, src/components/Modal/Modal.tsx
- Adds the `isContentPadded` flag (`true` by default) that removes the ModalContent padding when false. The issue that this addition addresses is that when the modal content needs to be scrollable, this padding pushes the scrollbar inside of the modal, which isn't wanted.
Also, by using these flags, no existing UIs will be affected.
=> [DS-364]: fix: add isContentPadded prop in Modal

src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextField/TextField.tsx
Inside `TextField` we take the props we need from the `props` object, which contains the `dataTestId` prop, and then spread that object both inside the `TextInputBase` component and the `input` element inside `TextField`.
That means we end up with a correct data-testid through `TextInputBase` and a `dataTestId` prop being passed to the `input` html element, which of course isn't recognized and produces this error: 
This PR omits said prop from the `input` element.
=> fix: fix textfield testid prop

src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/ExtendedColumnItem/ExtendedColumnItem.tsx, src/components/Tooltip/Tooltip.tsx, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
- Removes testid prop from tippy as it is not used.
PS. Running `yarn test . -u` updated the Table storyshots. While it looks like the data-testid prop was removed, I confirmed that the prop was never in the DOM to begin with.
=> [ds-360]: fix: removes testid prop from tippy to fix warning

src/components/Slider/Slider.tsx
- As decided in our last FE Discussions, the `onFinalChange` prop is renamed to `onBlur`
=> [NDS-341]: fix: rename onFinalChange to onBlur

src/components/Avatar/Avatar.style.ts, src/components/Avatar/Avatar.tsx, src/components/Avatar/Avatar.types.ts, src/components/Avatar/AvatarStack/AvatarStack.style.ts, src/components/Avatar/AvatarStack/AvatarStack.tsx, src/components/Avatar/AvatarStack/AvatarStack.types.ts, src/components/Avatar/AvatarStack/index.ts, src/components/Avatar/AvatarStack/utils.ts, src/components/Avatar/index.ts, src/components/Breadcrumb/Breadcrumb.tsx, src/components/Breadcrumb/BreadcrumbItem/BreadcrumbItem.tsx, src/components/Breadcrumb/Separator/Separator.tsx, src/components/Breadcrumb/index.ts, src/components/Card/Card.style.ts, src/components/Card/Card.tsx, src/components/Card/index.ts, src/components/Chip/Chip.style.ts, src/components/Chip/Chip.types.ts, src/components/Chip/components/Badge/Badge.tsx, src/components/Chip/components/Badge/index.ts, src/components/Chip/index.ts, src/components/Chip/utils.tsx
This is part ONE of the goal, to fix all internal types so they can be easily accessible on the root of the library by an external user.
Based on the ticket, what you are expecting to see is:
- Change all default Props naming we use on each component to ComponentNameProps so we can export and import easily
- Export all types and exported functions by default from each component
- Make all types by default exportable
=> [NDS-495] feat: change the first portion of components

src/components/CheckBox/CheckBox.style.ts, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/index.ts, src/components/Label/Label.style.ts, src/components/Label/Label.tsx, src/components/Label/index.ts, src/components/Radio/Radio.style.ts, src/components/Radio/Radio.tsx, src/components/Radio/index.ts, src/components/RadioGroup/index.ts, src/components/Select/Select.tsx, src/components/Select/components/SelectMenu/SelectMenu.style.tsx, src/components/Select/components/SelectMenu/SelectMenu.tsx, src/components/Select/components/SelectMenu/index.ts, src/components/Select/index.ts, src/components/Slider/Slider.tsx, src/components/Slider/components/SliderMark/SliderMark.tsx, src/components/Slider/components/SliderMark/index.ts, src/components/Slider/components/SliderThumb/SliderThumb.tsx, src/components/Slider/components/SliderThumb/index.ts, src/components/Slider/components/SliderTrack/SliderTrack.tsx, src/components/Slider/components/SliderTrack/index.ts, src/components/Slider/index.ts, src/components/Switch/Switch.tsx, src/components/Switch/index.ts, src/components/Toast/Toast.tsx, src/components/Toast/index.tsx, src/components/utils/ClickAwayListener/ClickAwayListener.tsx, src/components/utils/PositionInScreen/PositionInScreen.tsx
This is part THREE of the goal, to fix all internal types so they can be easily accessible on the root of the library by an external user.
Based on the ticket, what you are expecting to see is:
- Change all default Props naming we use on each component to ComponentNameProps so we can export and import easily
- Export all types and exported functions by default from each component
- Make all types by default exportable
=> [NDS-495] feat: change the third portion of components

src/components/Button/Button.style.ts, src/components/Button/Button.tsx, src/components/Button/ButtonLoader/ButtonLoader.tsx, src/components/Button/ButtonLoader/index.ts, src/components/Button/index.ts, src/components/ButtonBase/ButtonBase.style.ts, src/components/ButtonBase/ButtonBase.tsx, src/components/ButtonBase/index.ts, src/components/ButtonBase/utils.ts, src/components/Icon/Icon.tsx, src/components/Icon/index.ts, src/components/IconButton/IconButton.style.ts, src/components/IconButton/IconButton.tsx, src/components/IconButton/index.ts, src/components/SearchField/SearchField.tsx, src/components/SearchField/SearchFieldShowcase.tsx, src/components/SearchField/index.ts, src/components/TextArea/TextArea.tsx, src/components/TextArea/index.ts, src/components/TextField/TextField.tsx, src/components/TextField/index.ts, src/components/TextInputBase/TextInputBase.style.ts, src/components/TextInputBase/TextInputBase.tsx, src/components/TextInputBase/index.ts, src/utils/common.ts
This is part TWO of the goal, to fix all internal types so they can be easily accessible on the root of the library by an external user.
Based on the ticket, what you are expecting to see is:
- Change all default Props naming we use on each component to ComponentNameProps so we can export and import easily
- Export all types and exported functions by default from each component
- Make all types by default exportable
=> [NDS-495] feat: change the second portion of components

src/components/Notification/Banner/Banner.tsx, src/components/Notification/Banner/index.tsx, src/components/Notification/InlineNotification/InlineNotification.tsx, src/components/Notification/InlineNotification/index.tsx, src/components/Notification/NotificationVisual/NotificationVisual.tsx, src/components/Notification/NotificationVisual/index.tsx, src/components/Notification/NotificationsContainer/NotificationsContainer.tsx, src/components/Notification/NotificationsContainer/index.ts, src/components/Notification/Snackbar/Snackbar.tsx, src/components/Notification/Snackbar/index.tsx, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx, src/components/Notification/subcomponents/CompactNotification/index.tsx, src/components/Table/Table.tsx, src/components/Table/components/ExtendedColumnItem/ExtendedColumnItem.tsx, src/components/Table/components/ExtendedColumnItem/index.ts, src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx, src/components/Table/components/TableCell/TableCell.tsx, src/components/Table/components/TableCell/index.ts, src/components/Table/components/TableRow/TableRow.tsx, src/components/Table/components/TableRow/index.ts, src/components/Table/components/TableRowWrapper/TableRowWrapper.tsx, src/components/Table/components/TableRowWrapper/index.ts, src/components/Table/index.ts
This is the SEVENTH part and last one of the goal, to fix all internal types so they can be easily accessible at the root of the library by an external user.
Based on the ticket, what you are expecting to see is:
- Change all default Props naming we use on each component to ComponentNameProps so we can export and import easily
- Export all types and exported functions by default from each component
- Make all types by default exportable
=> [NDS-495] feat: change the 7th portion of components

src/theme/borderRadius.ts, src/theme/borderWidth.ts, src/theme/boxShadow.ts, src/theme/constants/borderRadius.ts, src/theme/constants/borderWidth.ts, src/theme/constants/boxShadow.ts, src/theme/constants/opacity.ts, src/theme/constants/sizing.ts, src/theme/index.ts, src/theme/opacity.ts, src/theme/sizing.ts, src/theme/types.ts, src/theme/utils.ts
[NDS-494](https://orfium.atlassian.net/browse/NDS-494)
[part IV of [NDS-489](https://orfium.atlassian.net/browse/NDS-489)]
In this PR the leftovers of the global theme reconfiguration are implemented.
That includes: 
- `border-width`
- `opacity`
- `border-radius`
- `opacity`
- `sizing`
=> [NDS-494] theme reconfiguration leftovers

src/components/List/List.style.ts, src/components/List/__snapshots__/List.stories.storyshot, src/components/List/utils.tsx, src/components/Select/Select.stories.mdx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot
This ticket introduces the option to pass a helper text to list item option.
Also , fixes the cursor on disabled list options
Ticket: https://orfium.atlassian.net/browse/NDS-589
Updated snaps and added case for helperText.
Added tests that helperText is visible
=> [NDS-589] Feat / add helper text to list item

.github/workflows/chromatic.yml, .github/workflows/pr.yml, .storybook/main.ts, src/components/DatePicker/utils.ts
Datepicker has the wrong date when opens. Although the values selected are correct. 
If you have selected values to 1/1/2023 for datepicker and you open to select a date you can see that the background is set to the fake date of 2020
Experimental version for testing: https://www.npmjs.com/package/@orfium/ictinus/v/4.55.1-alpha.0
Visually the problem
* Nothing changed for the project
* already tested locally against MET
=> [NDS-590] fix: add fake date to only affect storybook as intended

src/components/Notification/Banner/Banner.tsx, src/components/Notification/InlineNotification/InlineNotification.tsx, src/components/Notification/Notification.stories.mdx, src/components/Notification/Notification.style.ts, src/components/Notification/Notification.tsx, src/components/Notification/NotificationVisual/NotificationVisual.style.tsx, src/components/Notification/NotificationVisual/NotificationVisual.tsx, src/components/Notification/Snackbar/Snackbar.style.ts, src/components/Notification/Snackbar/Snackbar.tsx, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx, src/components/Notification/subcomponents/NotificationActionsArea/NotificationActionsArea.tsx, src/components/Notification/subcomponents/NotificationActionsArea/index.ts, src/components/Toast/Toast.style.ts, src/components/Toast/Toast.tsx
[NDS-623](https://orfium.atlassian.net/browse/NDS-623)
- Make `primaryCTA`, `primaryCTALabel`, `secondaryCTA`, `secondaryCTALabel` optional for all types of Notifications.
- Add `hasMinimumHeight` to Toast component (defaults to `true` so it doesn't break all current usages). This is needed for the Toast Notification in order to support the case of no CTAs. 
- Minor style changes for Notifications to support the case of no CTAs.
- Create `NotificationActionsArea` to reduce duplicate code. This component includes the Actions for `ToastNotification` and `Snackbar`
[NDS-623]: https://orfium.atlassian.net/browse/NDS-623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-623] make notification actions optional [v4.5]

src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap, src/hooks/__snapshots__/useSearchQueryParams.stories.storyshot, src/hooks/__tests__/useSearchQueryParams.test.ts, src/hooks/index.ts, src/hooks/storyUtils/DemoUseSearchQueryParams.tsx, src/hooks/useSearchQueryParams.stories.mdx, src/hooks/useSearchQueryParams.ts
The `useSearchQueryParams` hook, returns the URL search query parameters as a key - value plain object (**Record<string, string>**). Keep in mind that this hook can only be used into a `react-router-dom` context.
- Unit testing
=> [FE-58] feat: add useSearchQueryParams hook

build-storybook.log, src/components/CheckBox/CheckBox.stories.mdx, src/components/CheckBox/CheckBox.tsx
This PR solves a problem with the CheckBox documentation where the `Props` weren't visible 
New
=> fix: rename checkbox to fix props render on storybook

src/components/Table/Table.tsx
- Fixes an issue where the `onSort` callback was always called once during the initial rendering phase of the component, which wasn't expected or ideal.
- General cleanup of the file and completed a TODO item
=> [NDS-670]: fix: fixes issue where onSort was called on initial render

src/components/SearchField/SearchField.tsx, src/components/SearchField/__snapshots__/SearchField.stories.storyshot
This fix solves the problem with SearchField small case where after the update of the TextField went from 36px to 28px. Also it fixes the fontSize of sm from 12px to 13px. 
This happened due to the fact that SearchField uses the TextField as the base component.
We want a special case for SearchFields and their small case to be 36px and break the rule of 28px. This will be revisited in v5.
Old
New
Snapshots
=> [NDS-698] fix(SearchField): add unique case of 36 height on small size

package.json, src/components/NumberField/NumberField.stories.mdx, src/components/NumberField/NumberField.style.ts, src/components/NumberField/NumberField.test.tsx, src/components/NumberField/NumberField.tsx, src/components/NumberField/__snapshots__/NumberField.stories.storyshot, src/components/NumberField/components/Stepper/Stepper.style.ts, src/components/NumberField/components/Stepper/Stepper.tsx, src/components/NumberField/components/Stepper/index.ts, src/components/NumberField/index.ts, src/components/TextField/TextField.tsx, src/hooks/useFieldUtils.tsx, src/test/setup.ts, yarn.lock
[NDS-705](https://orfium.atlassian.net/browse/NDS-705)
[NDS-705]: https://orfium.atlassian.net/browse/NDS-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-705] NumberField [v5]

.storybook/preview.tsx, src/components/Chart/Chart.stories.mdx, src/components/Select/Select.tsx, src/components/Table/Table.stories.mdx
[NDS-758](https://orfium.atlassian.net/browse/NDS-758)
[NDS-772](https://orfium.atlassian.net/browse/NDS-772)
[NDS-758]: https://orfium.atlassian.net/browse/NDS-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDS-772]: https://orfium.atlassian.net/browse/NDS-772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-758 & NDS-772] select option click handler not triggered & Table documentation [v4]

src/components/Select/Select.tsx, src/components/Select/hooks/useMultiselectUtils.ts
[NDS-798](https://orfium.atlassian.net/browse/NDS-798)
In this PR: 
- Single Select: Backspace triggers the `handleSelectedOption` callback (external prop) with undefined.
- Multi Select: While BackSpace already deletes the last item from the inner state of selected options, it now also triggers the `onOptionDelete` callback (external prop) with the last item of the selectedOptions[] as an argument (this callback was only triggered when the X icon of the Chip-Option was clicked)
[NDS-798]: https://orfium.atlassian.net/browse/NDS-798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-798] fix: select backspace does not change value [v4]

src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/Select/types.ts, src/components/storyUtils/SelectShowcase/SelectShowcase.tsx
[NDS-807](https://orfium.atlassian.net/browse/NDS-807)
In this PR: 
- the Backspace issue is resolved: when Backspace is clicked on SingleSelect while the input value equals the selected option's label, then the Select will be cleared (that also fixes the issue of non-searchable Select where you cannot clear the field)
- as implemented on v4, the empty state of Select from now on is `undefined` ; so when the field is cleared, the onChange is called with `undefined` as an argument.
- Typos are fixed.
- Async Select Showcase wasn't working properly; now it's fixed.
[NDS-807]: https://orfium.atlassian.net/browse/NDS-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-807] fix: select backspace does not clear value [v5]

src/components/Avatar/Avatar.style.ts, src/components/Avatar/Avatar.tokens.ts, src/components/Avatar/__snapshots__/Avatar.stories.storyshot, src/components/Avatar/__snapshots__/AvatarStack.stories.storyshot, src/components/Button/Button.tokens.ts, src/components/ButtonBase/ButtonBase.style.ts, src/components/Chip/__snapshots__/Chip.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/ThemeProvider/ThemeProvider.style.ts, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/Typography/Typography.config.styles.ts, src/components/Typography/Typography.stories.mdx, src/components/Typography/Typography.style.ts, src/components/Typography/Typography.tsx, src/components/Typography/__snapshots__/Typography.stories.storyshot, src/components/Typography/utils.ts, src/storybook/Showcases/TypographyTokensShowcase/TypographyTokensShowcase.tsx, src/theme/tokens/semantic/typography.ts, src/theme/tokens/semantic/variables/typography.ts, src/theme/tokens/utils/components.ts, src/theme/tokens/utils/parsers.ts
[NDS-809](https://orfium.atlassian.net/browse/NDS-809)
- Update Typography Tokens and Typography component with new typography variations.
- Update Typography Tokens Parsing Mechanism to simplify typography usage across components.
- Update Avatar and Button typography usages.
[NDS-809]: https://orfium.atlassian.net/browse/NDS-809?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-809] feat: revisit typography parsing mechanism [v5]

package.json, yarn.lock
This PR tends to solve all security alerts by npm/yarn audit
In resolutions are the packages used by storybook v6 that are vulnerable. I am updating them without changing the version on storybook. This will be fixed once we go to v7 storybook.
=> [NDS-821] fix: update all affected dependencies

.github/workflows/main.yml, environments/review.env, package.json
This PR changes the way we build for Review Apps to not build twice by introducing `prepare` and `prepublishOnly`
Also it fixed an issue with `he.jsxDEV is not a function emotion` where we were building having `NODE_ENV=staging` for reviews
=> fix: build storybook and prepublishonly script

src/index.ts
This PR adds the missing typography component on the exports. Furthermore it differentiate globals typography type from the component because the name is identical
=> fix(Typography): add exportation of component

src/components/Table/TableRowContext.ts, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx, src/components/Table/components/TableRowWrapper/TableRowWrapper.tsx, src/components/TruncatedContent/__snapshots__/TruncatedContent.stories.storyshot
Tooltip content is now only necessary if you actually want to show
something completely different than the cell content.
It is no longer required for cases where your cell content is not a
string
commit-id:c0571df4
---
**Stack**:
- #804 ⬅
- #803
⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*
=> feat: improve how table cell tooltipContent works

bin/migrate.mjs, codemods/buttonCodemod.ts, codemods/chipCodemode.ts, codemods/iconButtonCodemod.ts, docs/GettingStarted/Migration/COMPONENT_CHANGES.mdx, vite.codemods.config.ts
This PR introduces some codemods enhancements and a fix on types 
Codemods for `Chips` to transform to `Tags` weren't working.
Codemods for `Buttons` now transforms `size` prop and doesn't break `type` prop.
Fixing error on `cjs` files when you run migration
=> fix: update documentation and codemods

src/components/Table/Table.tsx, src/components/Table/hooks/useTable.tsx
[NDS-1013](https://orfium.atlassian.net/browse/NDS-1013)
[NDS-1013]: https://orfium.atlassian.net/browse/NDS-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: table not rerendering on data change

src/__storyshots__/Updated Components/Breadcrumb-BasicBreadcrumbs.snap, src/__storyshots__/Updated Components/Breadcrumb-GoBackTo.snap, src/__storyshots__/Updated Components/Breadcrumb-Playground.snap, src/__storyshots__/Updated Components/Breadcrumb-ThirdPartyRoutingLibrary.snap, src/__storyshots__/Updated Components/Link-LinkStyles.snap, src/__storyshots__/Updated Components/Link-LinkWithIcon.snap, src/__storyshots__/Updated Components/Link-Placement.snap, src/__storyshots__/Updated Components/Link-Playground.snap, src/__storyshots__/Updated Components/Link-Sizes.snap, src/__storyshots__/Updated Components/Link-ThirdPartyRoutingLibrary.snap, src/__storyshots__/Updated Components/Menu-MenuTriggers.snap, src/__storyshots__/Updated Components/Notifications/Inline Alert-Error.snap, src/__storyshots__/Updated Components/Notifications/Inline Alert-Informational.snap, src/__storyshots__/Updated Components/Notifications/Inline Alert-Neutral.snap, src/__storyshots__/Updated Components/Notifications/Inline Alert-Playground.snap, src/__storyshots__/Updated Components/Notifications/Inline Alert-Success.snap, src/__storyshots__/Updated Components/Notifications/Inline Alert-Warning.snap, src/components/ButtonBase/ButtonBase.tsx, src/components/InlineAlert/InlineAlert.stories.tsx, src/components/InlineAlert/InlineAlert.tsx, src/components/Link/Link.tsx, src/components/utils/Slots.tsx, src/components/utils/tests/Slots.test.tsx
`<SlotProvider />` manages and provides slot props to its descendants. It allows for the definition and inheritance of props for named slots in a component tree.
```jsx
// Register component with the useSlotProps() hook
function Button(props) {
props = useSlotProps(props, 'button');
return (
<button {...props}>{props.children}</button>
);
}
function ButtonsWithPadding(props) {
return (
<SlotProvider slots={{ button: { style: { padding: '1rem' } } }}>
{props.children}
</SlotProvider>
)
}
// Somewhere in the app
<ButtonsWithPadding>
<Button>Button 1</Button> // Gets 1rem padding
<Button>Button 2</Button> // Gets 1rem padding
</ButtonsWithPadding>
```
=> feat: slot provider

src/components/Breadcrumb/index.ts
Exporting types from breadcrumb
=> fix: export breadcrumb types

src/components/Tooltip/Tooltip.tsx
this PR makes the opacity of tooltip 1 as the react-tooltip puts opacity by default
=> fix(tooltip): set opacity to 1 for consistent visibility

.eslintignore, .eslintrc.json, .releaserc, package.json, pnpm-lock.yaml, postcss.config.mjs, tsconfig.node.json, vite.config.d.ts, vite.vars.config.ts
Make a separate bundle for css vars `@orfium/ictinus/vars.css` to be consumed by external projects.
- Add `postcss` config to automatically transform px to rem in css outputs.
- Cleanup `eslint` config and fix malformed `.releaserc`
=> feat: separate css vars output

.changeset/stale-toys-check.md, package.json, pnpm-lock.yaml
- Updated vitest dependency in package.json and pnpm-lock.yaml to version 3.2.4.
- Adjusted related dependencies and peer dependencies to align with the new version.
=> chore: upgrade vitest to version 3.2.4
