src/components/Pagination/index.ts, src/index.tsx
=> Export Pagination

src/components/Radio/Radio.style.ts
This PR fixes the  missing return types errors when adding the project as a dependency.
=> Radio add return types on styles

src/components/Pagination/Pagination.tsx
Fix pagination colors with types after some changes on the icons after introducing icon buttons etc
=> fix pagination types and coloring

src/components/Table/Table.tsx, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
This PR adds the align prop to Cell in order to customize the alignment  of the Cell.
=> Table Row Align Cell prop

src/components/Select/Select.tsx
Added value property to select for forms.
=> Test With Value on select

src/hooks/usePagination.ts
This PR resolves an issue when navigating with pagination the functions that are reading current page doesnt refresh on the page change
=> fix pagination navigation

src/components/TextField/TextField.style.ts
This PR fixes the problem that when there was in error the background was transparent
=> fix text field background on error state

src/components/TextField/TextField.tsx
This PR adds type to all input to allow to change text to password etc
=> add optional type on input

src/components/Table/Table.tsx
This PR fixing the useMemo of table calculations when data are new to recalculate them.
This was causing some issues with columns width etc
=> small fix on useMemo 

src/components/Button/Button.style.ts, src/components/Select/Select.stories.mdx, src/components/Select/Select.tsx
This PR is a fix on the select and buttons for the disabled state
=> fix the disabled status of select and buttons

package.json, yarn.lock
Resolves the compatibility issue I was facing in a CRA project that uses jest 24
Closes #47
=> Move jest to peer dependencies

src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, yarn.lock
This PR fix a minor fault with spacing on expand button on row.
fix
Previous
=> add spacing to expandable button on row

src/index.tsx
This PR fixes the following:
Not all the created components were exposed from index.
=> Expose components

src/components/DatePicker/DatePicker.style.ts, src/components/TextField/TextField.style.ts, src/components/TextField/__snapshots__/TextField.stories.storyshot
This PR fix the label color across textfield and others because textfield was override the color of the label and this was leading to a different color
Updated test plans for text field
=> fix(label): fix label color to not be overwritten by textField

src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
This PR fixing the expand button that with rem size causing issues on other products 
problem
fix
Same tests
=> fix(table): remove the width with rem that causing size issues

src/components/Icon/__snapshots__/Icon.stories.storyshot, src/components/Icon/assets/iconSelector.ts, src/components/Icon/assets/star.svg, src/components/Icon/types.ts
This PR introduce a new icon - star. This icon is required in VH atm
No tests are necessary
=> feat(icon): add star icon to the collection

src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot
This PR solves a problem of the table that my latest performance PR caused where i check for selectedIds to show the top right area of the table which is wrong.
problem
=> fix(table): problem with right area

.releaserc
Style changes with or without scope should trigger a patch release. This PR changes the config that this could happen.
Also i added a docs functionality for the documentation that we will apply for also a patch version so we can keep track.
No screenshot necessary
No tests are necessary
=> feat: new release config for style and docs

src/components/Card/Card.stories.mdx, src/components/Card/Card.style.ts, src/components/Card/Card.tsx, src/components/Card/__snapshots__/Card.stories.storyshot, src/components/Card/index.ts, src/components/storyUtils/CardShowcase/CardShowcase.tsx, src/components/storyUtils/CardShowcase/index.ts, src/index.tsx, src/theme/elevation.ts, src/theme/index.ts
This PR implements the Card with its features as described in issue #116 
Resolves #116 
The card is a wrapper for children and thus can take different shapes
- Snapshot testing for the component
=> Feature Card

src/components/Notification/Banner/Banner.tsx, src/components/Notification/InlineNotification/InlineNotification.tsx, src/components/Notification/NotificationsContainer/NotificationsContainer.style.tsx, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx
Minor Fixes for **InlineNotification** and **NotificationsContainer**:
- Icon and Filling props optionality fixed
- NotificationsContainer is now in fixed position, not absolute
=> Fix/Notification Minor Fixes

src/components/Icon/__snapshots__/Icon.stories.storyshot, src/components/Icon/assets/iconSelector.ts, src/components/Icon/assets/pause.svg, src/components/Icon/assets/restart.svg, src/components/Icon/assets/resume.svg, src/components/Icon/types.ts
In this PR we introduce 3 new icons. Resume, Restart and Pause.
Updated snapshots
=> Feature: New icons

src/components/TopAppBar/TopAppBar.tsx, src/components/TopAppBar/TopAppBar.types.ts, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/TopAppBarShowcase.tsx
Exposes color prop for user menu.
=> chore(color): exposes color option for user menu

src/components/Pagination/Pagination.tsx, src/components/Pagination/__snapshots__/Pagination.stories.storyshot
Fixes pagination alignment to center
before:
after:
snapshot testing
=> fix(pagination): fixes pagination alignment to center

src/components/Select/Select.tsx
Current handleSelectedOption will be invoked as soon as the component mount.
This PR changes the behavior of handleSelectedOption. The callback will be invoked only when a user selects an option.
snapshots
=> fix(select): fixes handleSelectedOption invocation

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.tsx, src/components/Select/Select.tsx, src/components/TextField/TextField.tsx
(Possibly) Fixes TS errors that would emerge when trying to add generic HTML input attributes to the component (e.g. maxLength). 
Also changes types in other components that use the TextField, in order to accommodate the new changes.
=> fix(textfield): fixes input props causing a typescript error

src/components/TextField/TextField.tsx
Using Omit marked all HTMLInputProps as required and type errors were thrown. Wrapped it in Partial<>
=> fix(textfield): fixes issue where omit changed all props to required

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.tsx, src/components/Select/Select.tsx
Size prop resolved to undefined due to conflict with the intrinsic input attribute `size`
=> fix: fixes issue where size prop across components resolves to undefined

package.json, src/components/DatePicker/Day/__snapshots__/Day.test.tsx.snap, src/components/DatePicker/Month/__snapshots__/Month.test.tsx.snap, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/test/utils.tsx, yarn.lock
From 2.7 to 2.8 version the prop that passed the selected value to the parent didn't work. This should fix the issue. Perhaps we should think of adding some unit tests too.
=> Fix: Select props should now have the selected value

src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Loader/Loader.style.tsx, src/components/Loader/Loader.tsx, src/components/Loader/__snapshots__/Loader.stories.storyshot
Completely change loader styling to emotion. 
Incorporate theme getColor util function to get the colors from our palette.
=> refactor(loader): change styling from styled-components to emotion

src/components/Menu/Menu.style.ts
This PR solves the last ui fix for the ictinus next version which is the alignment on the dropdown menu.
DESIGN QA
=> [DS-96] Fix/menu align

src/index.tsx
Dummy PR. Will bump version with new export paths.
=> fix: release new export paths

src/components/AssetMatching/components/Categories/Categories.tsx
fixes a condition whether we should display categories or not.
=> fix(condition): fixes category display condition

src/components/AssetMatching/Assetmatching.tsx
Exposes the prop for handling the checkbox's click event.
=> fix(onCheck): adds the onCheck handler for checkbox 

src/components/AssetMatching/AssetMatching.stories.mdx, src/components/AssetMatching/Assetmatching.tsx, src/components/AssetMatching/components/ActionsToolbox/ActionsToolbox.tsx, src/components/AssetMatching/components/ActionsToolbox/PrimaryActions.tsx, src/components/AssetMatching/components/ActionsToolbox/SecondaryActions.tsx, src/components/AssetMatching/components/CheckBoxContainer/CheckBoxContainer.tsx, src/components/AssetMatching/components/SectionHeader/SectionHeader.style.ts, src/components/AssetMatching/components/SectionHeader/SectionHeader.tsx, src/components/AssetMatching/components/utils.tsx, src/components/storyUtils/AssetMatchingShowcase/BulkActionsShowcase.tsx, src/hooks/useCheck.ts
[jira task](https://orfium.atlassian.net/secure/RapidBoard.jspa?rapidView=40&modal=detail&selectedIssue=DS-119)
- adds bulk actions showcase because this will help other devs to understand the logic of the bulk actions selector.
- adds button style configuration prop for SectionHeader component
- fixes state update issues due to complex logic on multi-selection
showcase can be previewed [here](https://ictinus-feat-asset-matc-fu99r7.herokuapp.com/?path=/story/design-system-asset-matching--bulk-actions-showcase)
updates snapshots
=> [DS-119]: feat: adds bulkActions showcase

src/components/TopAppBar/components/Search/Search.style.ts
change border radius on TopAppBar's  Search bar according to designs
[DS-ticket](https://orfium.atlassian.net/browse/DS-118)
=> [DS-118] Correct corner radius in Top Nav Search Bar

src/components/AssetMatching/Assetmatching.tsx, src/components/AssetMatching/components/ActionsToolbox/ActionsToolbox.tsx, src/components/AssetMatching/components/SectionHeader/SectionHeader.tsx, src/components/storyUtils/AssetMatchingShowcase/AssetMatchingShowcase.tsx, src/components/storyUtils/AssetMatchingShowcase/BulkActionsShowcase.tsx, src/components/storyUtils/AssetMatchingShowcase/SectionHeaderShowcase.tsx
- Adds prop for custom action element.
- Updates showcases to cover missing use cases.
=> [DS-119]: feat(asset-matching): adds prop for custom action element 

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/TextArea/TextArea.style.ts, src/components/TextField/TextField.style.ts, src/components/ThemeProvider/ThemeProvider.tsx, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/TopAppBar/components/UserMenu/UserMenu.style.ts, src/components/TopAppBar/components/UserMenu/UserMenu.tsx, src/components/utils/TextInputWrapper/TextInputWrapper.style.ts, src/theme/typography.ts
In this pr we want to change the font-weight of the topAppBar's user field to 500. For that reason we introduce font-weight: 500 (medium) in typography, and change typography.weights,black to 900 instead of 700 to match [Google Fonts documentation](https://fonts.google.com/specimen/Roboto) 
[DS ticket](https://orfium.atlassian.net/browse/DS-120)
=> [DS-120]: Correct font weight for user field in Top App Bar

src/components/TopAppBar/TopAppBar.tsx, src/components/TopAppBar/TopAppBar.types.ts, src/components/TopAppBar/components/Search/Search.tsx
introduce the searchDefaultValue prop for the TopAppBar component
[DS-ticket](https://orfium.atlassian.net/browse/DS-128)
=> [DS-128]: add searchDefaultValue prop

src/components/TopAppBar/TopAppBar.test.tsx, src/components/TopAppBar/TopAppBar.tsx, src/components/TopAppBar/TopAppBar.types.ts, src/components/TopAppBar/components/Search/Search.tsx
Introduce the onKeyPressHandler prop for the TopAppBar component
[DS-ticket](https://orfium.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DS&modal=detail&selectedIssue=DS-129)
=> [DS-129]: add onKeyPressHandler prop

src/components/CheckBox/CheckBox.style.ts, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot
[DS-127](https://orfium.atlassian.net/browse/DS-127)
=> fix: checkbox icons misalignment [DS-127]

src/hooks/useBreakpoints.tsx, src/index.tsx
In this PR we expose queriesSizes to use in css media queries.
=> feat/expose queriesSizes

src/components/Pagination/Pagination.tsx, src/components/Pagination/__snapshots__/Pagination.stories.storyshot
Implement Pagination component fixes, as described here: [DS-132]
Before:
After:
[DS-132]: https://orfium.atlassian.net/browse/DS-132
=> fix(pagination): apply style fixes [DS-132]

src/components/Card/Card.stories.mdx, src/components/Card/Card.style.ts, src/components/Card/Card.tsx, src/components/Card/__snapshots__/Card.stories.storyshot, src/components/Modal/Modal.stories.mdx, src/components/Modal/Modal.style.ts, src/components/Modal/Modal.tsx, src/components/Modal/ModalContent/ModalContent.style.ts, src/components/Modal/ModalContent/ModalContent.tsx, src/components/Modal/__snapshots__/Modal.stories.storyshot, src/components/storyUtils/CardShowcase/CardShowcase.style.tsx, src/components/storyUtils/CardShowcase/CardShowcase.tsx, src/components/storyUtils/ModalShowcase/ModalShowcase.tsx
[DS-121](https://orfium.atlassian.net/browse/DS-121)
This PR includes: 
- modal UI fixes  
- Card Component update (2 new props added)
=> fix: modal ui fixes and card props update

src/components/Breadcrumb/BreadcrumbCollapsed/BreadcrumbCollapsed.tsx, src/components/Filter/Filter.stories.mdx, src/components/Filter/Filter.style.ts, src/components/Filter/Filter.test.tsx, src/components/Filter/Filter.tsx, src/components/Filter/__snapshots__/Filter.stories.storyshot, src/components/Filter/index.ts, src/components/Filter/types.ts, src/components/Filter/utils.ts, src/components/Menu/Menu.style.ts, src/components/Menu/Menu.tsx, src/components/storyUtils/FilterShowcase/FilterShowcase.tsx, src/components/storyUtils/FilterShowcase/index.ts, src/components/utils/DropdownOptions/index.tsx
implement the a simple filter component based on the design system (no search, no multi selection)
=> feat: add filter component

src/components/storyUtils/PaletteShowcase/PaletteShowcase.tsx, src/theme/palette.ts
this PR introduce a fix for all the type autofill for getColor function
=> fix(palette): fix types for getColor to have autofill

src/components/Filter/Filter.tsx
This PR solves the issue with builds because of the jsx import on the new component from the master
=> fix(filters): fix jsx import for new filters component after merge

src/components/Filter/Filter.stories.mdx, src/components/Filter/Filter.style.ts, src/components/Filter/Filter.test.tsx, src/components/Filter/Filter.tsx, src/components/Filter/__snapshots__/Filter.stories.storyshot, src/components/Filter/types.ts, src/components/Filter/utils.ts, src/components/storyUtils/FilterShowcase/FilterShowcase.tsx, src/components/utils/DropdownOptions/index.tsx
[DS-144](https://orfium.atlassian.net/browse/DS-144)
+ Design oversight in elevated style: “Visited” State should also have elevation. The only state in Elevated style that does not have elevation is focused. 
+ add a max hight for menu (253px)
+ Default option should always be the first list item and font should have medium weight - design oversight
+ If user has selected any other option than default it should be visible by opening menu
=> chore: qa design

src/theme/typography.ts
Change default font family from Lato to Roboto.
=> Feat/change default to Roboto

src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/Button.style.ts, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Drawer/__snapshots__/Drawer.stories.storyshot, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Modal/__snapshots__/Modal.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/ThemeProvider/__snapshots__/ThemeProvider.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap
This PR resolves a discrepancy between Figma and Ictinus on Button component font weight.
[Ticket](https://orfium.atlassian.net/browse/DS-183)
Updated snaps.
=> [DS-183] Feat/buttons update

src/components/Loader/__snapshots__/Loader.stories.storyshot, src/components/Loader/components/DotsLoader/DotsLoader.style.tsx, src/components/Loader/components/DotsLoader/DotsLoader.tsx, src/components/TextField/TextField.stories.mdx, src/components/TextField/__snapshots__/TextField.stories.storyshot
- fixes loader positioning in dom
[jira task](https://orfium.atlassian.net/browse/DS-176)
- updates snapshots
=> [DS-176]: Feat/ds 176

src/components/AssetMatching/components/Asset/Asset.style.ts, src/components/AssetMatching/components/Asset/AssetHeading.tsx
- this is an change request for the asset's icon size.
- changes the icon size from 24 to 16 px.
- fixes aligment between icon and h3.
=> [NO-JIRA]: fix - changes icon size and fixes icon alignment

package.json, src/components/AssetMatching/components/Asset/Asset.style.ts, src/components/AssetMatching/components/Asset/AssetExternalLink.tsx, src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.style.ts, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.stories.storyshot, src/components/Tooltip/index.ts, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx, src/components/storyUtils/TooltipShowcase/index.ts, src/index.tsx, src/storybook.test.ts, src/test/setup.ts, src/theme/index.ts, src/theme/overrides.ts, yarn.lock
This PR introduce a new component for our system, a tooltip. 
This tooltip is only holding plain text. You can define position but based on the screen this will change if there is no space to show it on the pre-defined location.
A new system config name `overrides` was introduced. Its mainly for tooltip ATM in order to define its color and shade for the whole system. The logic is that tooltip will have only one color that will be unique for the whole project. This way we may introduce new overrides in the future.
[Ticket](![image](https://user-images.githubusercontent.com/6433679/122205532-04c8de80-cea9-11eb-9fe4-d20035b78b1a.png))
[Design](https://www.figma.com/file/8kMPBNYHHXz2AtkzeeDmk5/Design-System?node-id=659%3A13)
Note: Asset Matching was changed due to the fact we were using …
=> [DS-153] Feature/tooltip

src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx
This PR is only for the selected few brave enough to handle such a change.
Changed the expandable icon from `arrowDown` to `chevronSmallDown`.
[Ticket](https://orfium.atlassian.net/browse/DS-190)
=> [DS-190] feat/change expanded icon

src/index.tsx
In this MR we just export the Filter component.
=> chore: Export filter component

src/components/AssetMatching/AssetMatching.stories.mdx, src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/AssetMatching/components/Asset/AssetExternalLink.tsx, src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Drawer/__snapshots__/Drawer.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Modal/__snapshots__/Modal.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/ThemeProvider/__snapshots__/ThemeProvider.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/storyUtils/AssetMatchingShowcase/ActionsToolBoxShowcase.tsx
- adds new prop for html button type 
- removes deprecated prop from showcase
- updates all related snapshots
=> [NO-JIRA]: Fix/button type

.github/workflows/ci.yml, .releaserc, package.json, yarn.lock
This PR introduce a new mechanism to release ictinus to github-packages as well. The vision is to have everything under packages here but to not break the Ictinus project. So only ictinus will be on npm registry
=> [NO-JIRA] feat(workflow): add ci release for github packages

src/components/Drawer/Drawer.tsx
=> fix: change type of render prop to Drawer

src/components/Filter/components/Options/Options.tsx, src/components/Filter/components/SearchInput/SearchInput.tsx, src/components/storyUtils/FilterShowcase/AsyncFilterShowcase.tsx, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
removing all jsx pragma that left after merge and now is causing problem on building the next release
=> fix(build): small fix after merge for jsx

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/DatePicker/utils.ts
[DS-212]
Adds placeholder text for each datepicker type as shown in the designs, as well as a prop to have that placeholder be today's date.
[DS-212]: https://orfium.atlassian.net/browse/DS-212
=> feat(datepicker): add placeholder text option

src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/utils.ts
Hotfix.
Change default value of newly added prop, because it added a breaking change.
Minor renaming for readability.
=> [NO-JIRA] fix(datepicker): change default value for placeholder check

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
[DS-220](https://orfium.atlassian.net/browse/DS-220)
=> [DS-220] table header and expandable rows misalignment

src/components/Table/Table.style.ts, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot
[ticket](https://orfium.atlassian.net/browse/DS-229)
Updated snaps
=> [DS-229] Fix / Table header width when expandable

src/components/Modal/Modal.stories.mdx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx, src/components/storyUtils/ModalShowcase/ModalShowcase.tsx, src/hooks/useEscape.ts, src/index.tsx
Added an option that defines if the modal should close with esc button or not, default value is true.
[DS-243](https://orfium.atlassian.net/browse/DS-243)
=> feat: [DS-243] close modal on esc

src/components/Button/Button.style.ts, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/ButtonBase/ButtonBase.style.ts, src/components/ButtonBase/ButtonBase.tsx, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/storyUtils/AsyncButtonShowcase/AsyncButtonShowcase.tsx, src/hooks/useLoading.ts
- adds button type for buttons
- passes the event object as second argument in the click handler
- enhances button async showcases 
- updates snapshots
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> [NO-JIRA] Fixes button type and button click handler.

src/components/Modal/Modal.tsx
[DS-247](https://orfium.atlassian.net/browse/DS-247)
=> [DS-247] - Modal close button color issue

src/components/Select/Select.stories.mdx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot
[DS-246](https://orfium.atlassian.net/browse/DS-246)
=> [DS-246] - Select Dropdown disabled locked issue

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/TableRowContext.ts, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx, src/components/Table/components/TableRowWrapper/TableRowWrapper.tsx
[DS-249](https://orfium.atlassian.net/browse/DS-249)
=> [DS-249] feat: table with expandable rows action width

src/components/Button/Button.style.ts, src/components/Button/Button.tsx, src/utils/common.ts
Proposal.
- Fixes Button type errors.
[DS-251]
[DS-251]: https://orfium.atlassian.net/browse/DS-251
=> fix: fix button html prop type errors

.github/workflows/ci.yml
This PR upgrade the CI node version from `12` to `14.17` to resolve semantic release problem.
=> [important] Update CI node version

.github/workflows/ci.yml
This PR is to upgrade the node version in CI.
=> [NO-JIRA] chore/update ci to node 14.17

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/ButtonBase/ButtonBase.style.ts, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Modal/__snapshots__/Modal.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/ThemeProvider/__snapshots__/ThemeProvider.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap
GH issue: https://github.com/Orfium/orfium-ictinus/issues/369
TIcket: https://orfium.atlassian.net/secure/RapidBoard.jspa?rapidView=40&projectKey=DS&modal=detail&selectedIssue=DS-255
Update snaps
=> [DS-255] Fix/add focused state on button base

src/components/Button/Button.stories.mdx, src/components/Button/__snapshots__/Button.stories.storyshot
This PR fixes the issue of not showing the button story on the storybook sidebar.
old
new
=> fix(button): story with duplicate name caused error

.storybook/preview-head.html, src/components/Filter/utils.ts
This PR solves an issue where the transparent filter was actually having a white background. 
Also here is included a new background color for the canvas section that will match the Figma. With that we expect to catch errors like this.
=> fix(filter): transparent background from white to transparent

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot
ticket: https://orfium.atlassian.net/browse/DS-268
Update snapshots
=> [DS-268] Fix/ table checkbox shouldn't sticky stick

src/components/List/ListItem/ListItem.tsx, src/components/List/__snapshots__/List.stories.storyshot
[DS-274](https://orfium.atlassian.net/browse/DS-274)
_(for ictinus v3)_
=> fix: select with react-final-form issue [V3]

src/components/List/ListItem/ListItem.tsx, src/components/List/__snapshots__/List.stories.storyshot
[DS-274](https://orfium.atlassian.net/browse/DS-274) 
_(for ictinus v4)_
=> fix: select with react-final-form issue [V4]

src/components/Table/Table.stories.mdx, src/components/Table/Table.style.ts, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.style.ts, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/TableCell/TableCell.tsx
Add a new prop , `fixedCTA`  in order to have the CTA's fixed to top. 
Ticket: https://orfium.atlassian.net/browse/DS-273
Updated snapshots
=> [DS-273] : Feat/fixed cta's container

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Tooltip/Tooltip.tsx, src/components/storyUtils/TooltipShowcase/TooltipShowcase.style.ts, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
[DS-272](https://orfium.atlassian.net/browse/DS-272)
_(for ictinus v3)_
=> feat: tooltip add extra properties [V3]

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Tooltip/Tooltip.tsx, src/components/storyUtils/TooltipShowcase/TooltipShowcase.style.ts, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
[DS-272](https://orfium.atlassian.net/browse/DS-272)
_(for ictinus v4)_
=> feat: tooltip add extra properties [V4]

src/components/Menu/Menu.stories.mdx, src/components/Menu/Menu.tsx, src/components/Menu/__snapshots__/Menu.stories.storyshot
add disabled prop to menu 
ticket: https://orfium.atlassian.net/browse/DS-276
New story and updated storyshots
=> [VID-276] feat/disabled prop to menu

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot
Add prop to make table sorting work in only one way.
ticket: https://orfium.atlassian.net/browse/DS-275
Added story and updated storyshots
=> [VID-275] Feat/table configurable sort

src/components/Filter/Filter.style.ts, src/components/Filter/Filter.tsx, src/components/Filter/components/Options/Options.tsx, src/components/List/List.style.ts, src/components/List/List.tsx, src/components/List/NormalList/NormalList.style.ts, src/components/List/NormalList/NormalList.tsx, src/components/List/__snapshots__/List.stories.storyshot, src/components/storyUtils/FilterShowcase/FilterShowcase.tsx
- Removes padding outside of Filter component
- Fixes border radius issues, as shown on the ticket [DS-284]
After the changes:
[DS-284]: https://orfium.atlassian.net/browse/DS-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: correct filter border radius and paddings

src/components/Button/__snapshots__/Button.stories.storyshot, src/components/DatePicker/Day/__snapshots__/Day.test.tsx.snap, src/components/DatePicker/Month/__snapshots__/Month.test.tsx.snap, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap, src/theme/palette.config.ts, src/theme/palette.ts
[Ticket](https://orfium.atlassian.net/browse/DS-280)
In this PR we change the blue base color from #2979FF to #175BF5.
=> [DS-280]: style: change blue base color

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx, src/components/TruncatedContent/TruncatedContent.stories.mdx, src/components/TruncatedContent/TruncatedContent.style.tsx, src/components/TruncatedContent/TruncatedContent.test.tsx, src/components/TruncatedContent/TruncatedContent.tsx, src/components/TruncatedContent/__snapshots__/TruncatedContent.stories.storyshot, src/components/TruncatedContent/index.ts, src/index.tsx
- Adds a generic component that can be used to truncate text based on the parent's max width. On truncation, it shows a tooltip. Can be used inside a table or standalone.
=> feat: add tooltip on truncation functionality

src/components/Avatar/Avatar.stories.mdx, src/components/Avatar/Avatar.style.ts, src/components/Avatar/Avatar.tsx, src/components/Avatar/__snapshots__/Avatar.stories.storyshot, src/components/Chip/Chip.stories.mdx, src/components/Chip/Chip.style.ts, src/components/Chip/Chip.test.tsx, src/components/Chip/Chip.tsx, src/components/Chip/__snapshots__/Chip.stories.storyshot, src/components/Chip/components/Badge/Badge.style.ts, src/components/Chip/components/Badge/Badge.tsx, src/components/Chip/components/Badge/index.ts, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/storyUtils/ChipShowcase/ChipShowcase.tsx, src/theme/typography.ts
[Jira-Ticket](https://orfium.atlassian.net/browse/DS-258)
[Designs](https://www.figma.com/file/8kMPBNYHHXz2AtkzeeDmk5/Design-System-V4---Working-File?node-id=10062%3A105272)
[Avatar-Designs](https://www.figma.com/file/8kMPBNYHHXz2AtkzeeDmk5/Design-System-V4---Working-File?node-id=9697%3A110165)
In this PR we introduce the new Designs for the Chip component.
For our needs, we also introduce a new size option ('xxxs') for the Avatar component along with a new font-size option (8px).
=> [DS-258]: Feat/chip refactoring

src/components/Drawer/Drawer.style.ts
[Ticket](https://orfium.atlassian.net/browse/DS-279)
=> [DS-279]: style(drawer): border-right changed

docs/system/THEME.stories.mdx, src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Card/__snapshots__/Card.stories.storyshot, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/Toast/__snapshots__/Toast.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/theme/elevation.ts
[Ticket](https://orfium.atlassian.net/browse/DS-224)
=> [DS-224]: style(elevation): elevation updated

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Tooltip/Tooltip.style.ts, src/components/TruncatedContent/__snapshots__/TruncatedContent.stories.storyshot
[Ticket](https://orfium.atlassian.net/browse/DS-278)
=> [DS-278]: style(tooltip): text align changed to start

src/components/Table/Table.stories.mdx, src/components/Table/Table.style.ts, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.style.ts, src/components/Table/components/TableCell/TableCell.tsx, src/components/Table/utils/utils.ts, src/components/TruncatedContent/__snapshots__/TruncatedContent.stories.storyshot
[Ticket](https://orfium.atlassian.net/browse/DS-277)
=> [DS-277]: style(table): fixed header border color updated

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/CheckBox/CheckBox.stories.mdx, src/components/CheckBox/CheckBox.style.ts, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot
[Ticket](https://orfium.atlassian.net/browse/DS-291)
[Designs](https://www.figma.com/file/3deO7jGtkly8ij4TiIUpzY/Design-System-V4.5-(%E2%9D%84%EF%B8%8FDO-NOT-EDIT)?node-id=10283%3A104355l)
=> [DS-291]: feat(checkbox): outlined style updated

src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx
[Ticket](https://orfium.atlassian.net/browse/DS-194)
=> [DS-194]: feat(table): outlined checkboxes added

src/components/Notification/Banner/Banner.tsx, src/components/Notification/InlineNotification/InlineNotification.tsx, src/components/Notification/Notification.stories.mdx, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Notification/subcomponents/CompactNotification/CompactNotification.style.ts, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx
ticket: [DS-312](https://orfium.atlassian.net/browse/DS-312)
Updated snapshots
=> [DS-312] feat/add custom component to inline notifications 

.storybook/preview.tsx, src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/components/DatePicker/Month/__snapshots__/Month.test.tsx.snap, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Icon/__snapshots__/Icon.stories.storyshot, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Loader/__snapshots__/Loader.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Modal/__snapshots__/Modal.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Radio/__snapshots__/Radio.stories.storyshot, src/components/Radio/__snapshots__/Radio.test.tsx.snap, src/components/RadioGroup/__snapshots__/RadioGroup.stories.storyshot, src/components/Toast/__snapshots__/Toast.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap, src/components/storyUtils/ThemeWrapper/ThemeWrapper.tsx, src/test/utils.tsx
Changed Primary color to Blue and Secondary color to Teal.
[Ticket](https://orfium.atlassian.net/browse/DS-307)
Buttons with primary and secondary.
Updated snapshots.
=> [DS-307] Feat/change primary and secondary colors

src/components/List/ListItem/ListItem.style.ts, src/components/List/ListItem/ListItem.tsx, src/components/List/__snapshots__/List.stories.storyshot, src/components/Select/Select.stories.mdx, src/components/Select/Select.style.ts, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot
[Ticket](https://orfium.atlassian.net/browse/DS-298)
Also 
- we resolve [this bug](https://orfium.atlassian.net/browse/DS-298?focusedCommentId=24169)
- we make sure all listItems have ```cursor: pointer;``` property
- we fixed the disabled option bug
=> [DS-298]: feat(select): add triangle icons

src/components/ExpandCollapse/ExpandCollapse.tsx
=> Change ExpandCollapse.tsx children type to ReactNode

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/ButtonBase/ButtonBase.tsx, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Modal/__snapshots__/Modal.stories.storyshot, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/ThemeProvider/__snapshots__/ThemeProvider.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap
Resolves #419 . Snapshots had to be updated too.
=> fix: Set button type to 'button' by default

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.style.ts, src/components/TruncatedContent/__snapshots__/TruncatedContent.stories.storyshot, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
[Ticket](https://orfium.atlassian.net/browse/DS-321)
=> [DS-321]: fix(tooltip): add missing css props

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/Select/Select.style.ts, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.style.ts, src/components/TextInputBase/TextInputBase.tsx, src/components/TextInputBase/config.ts, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap, src/theme/states/disabled.ts, src/theme/states/focus.ts, src/theme/states/hover.ts, src/theme/states/pressed.ts, src/theme/states/utils.ts
Integration of global states to text input base. ( duh, it says in tittle dum dum ) 
This uses the same styles and patterns described in https://github.com/Orfium/orfium-ictinus/pull/441
Major changes that happened in this PR:
- We only support outlined variant. I have not yet removed the types as this is a breaking change, but all types return the outlined version. 
- Abstracted part of the styling for the text input base component in a config. 
- Refactored the way we style text input base as it was a bit complicated.
- Focused state is the same as pressed/active state. When you focus an input you can write.
In general, no further changes where needed in the global states functions. I did the bare minimum in order to not get outside the scope of the ticket. I could have also done other …
=> [DS-305] Feat / Global States - integration with text field

src/components/AssetMatching/__snapshots__/AssetMatching.stories.storyshot, src/components/Breadcrumb/__snapshots__/Breadcrumb.stories.storyshot, src/components/Button/Button.stories.mdx, src/components/Button/Button.style.ts, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap
Fixing a small bug existing only in v3.
Ticket: https://orfium.atlassian.net/browse/DS-315
=> [DS-315] fix: icon padding and icon container

src/components/Radio/Radio.stories.mdx, src/components/Radio/Radio.style.ts, src/components/Radio/Radio.tsx
Nothing major. Minor changes in order to follow the way of coding the rest of the DS components are using.
ticket: https://orfium.atlassian.net/browse/DS-306
=> [DS-306] refactor/radio

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Filter/Filter.style.ts, src/components/Filter/utils.ts, src/theme/states/tests/states.test.ts
[Ticket ](https://orfium.atlassian.net/browse/DS-305)
Integration with Global states. 
This one has the exception that in pressed the global rules do not apply.
I haven't implemented some kind of config in this. It's something that I would like to further discuss and decide in the next FE chapter discussion in order to further implement in the future.
Updated snaps
=> [DS-305] Feat / filter integration 

src/components/Avatar/Avatar.stories.mdx, src/components/Avatar/__snapshots__/Avatar.stories.storyshot, src/components/Overlay/Overlay.stories.mdx, src/components/Overlay/Overlay.style.ts, src/components/Overlay/Overlay.test.tsx, src/components/Overlay/Overlay.tsx, src/components/Overlay/__snapshots__/Overlay.stories.storyshot, src/components/Overlay/index.ts, src/components/storyUtils/OverlayShowcase/OverlayShowcase.tsx, src/components/storyUtils/OverlayShowcase/index.ts, src/index.tsx
[Ticket](https://orfium.atlassian.net/browse/DS-302)
=> [DS-302]: Feat/overlay

.github/workflows/ci.yml
This PR should add an auto-publishing step of the docs to the docs repo
=> doc: deploy documentation on push to master

.github/workflows/ci.yml
This PR changes the target folder used to copy the generated docs from. Here we already use the filename docs for other purposes.
=> [NO-JIRA] fix/ci workflow for docs creation

.github/workflows/sonar.yml, sonar-project.properties
In this PR we add the config and workflow for sonar cube analysis.
=> [NO-JIRA] feat/ sonar cube 

src/components/Button/Button.style.ts, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/Day/Day.style.ts, src/components/Drawer/Navigation/Navigation.style.ts, src/components/IconButton/IconButton.style.ts, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Notification/subcomponents/CompactNotification/CompactNotification.style.ts, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx, src/components/Select/Select.tsx, src/components/utils/DropdownOptions/index.tsx, src/theme/functions.ts, src/theme/utils.ts
Remove dead/unused code from ictinus. This includes:
- Unused imports
- Unused variables
- Commented code
Also fixed a style that I happened to find was wrong. That why there is an updated snapshot.
Ticket: https://orfium.atlassian.net/browse/DS-339
Updated snapshots for fixed style
=> [DS-339] Fix/remove dead code

src/components/ButtonBase/ButtonBase.style.ts, src/components/ButtonBase/utils.ts
This is a first attempt to refactor a function labeled for high [cognitive complexity](https://www.sonarsource.com/resources/white-papers/cognitive-complexity/#:~:text=Cognitive%20Complexity%20offers%20a%20new,strikes%20developers%20as%20intuitively%20right.&text=Cognitive%20Complexity%20breaks%20from%20the,models%20to%20assess%20software%20maintainability.). Analysis runs on master releases only for now.
Ticket: https://orfium.atlassian.net/browse/DS-340
=> [DS-340] fix/button refactor to reduce cognitive complexity

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/utils/PositionInScreen/PositionInScreen.style.tsx, src/components/utils/PositionInScreen/PositionInScreen.tsx
- Fixes the z-index issue that caused the popup to show below some components in certain resolutions (e.g. TopBar)
- Fixes a cheeky id :)
=> fix: fix z-index issue for position in screen component

src/components/DatePicker/DatePicker.tsx
=> chore: add DD/MM/YYYY as a date format type

src/components/DatePicker/DatePicker.tsx
- reverts PR because of wrong commit message
=> Revert "chore: add DD/MM/YYYY as a date format type"

src/components/DatePicker/DatePicker.tsx
- Adds `DD/MM/YYYY` date format in type
=> feat: add DD/MM/YYYY as a date format type

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/SearchField/SearchField.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/TextArea.tsx, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.tsx
- Adds dataTest ids to error messages of form fields, in order to help QA Engineers successfully test negative scenarios
=> [DS-351]: feat: add dataTest ids in error messages of form fields

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/Select/Select.style.ts, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextArea/TextArea.style.ts, src/components/TextArea/TextArea.tsx, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.style.ts, src/components/TextInputBase/config.ts, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap
- Replaces min-width with the DS value (150px)
- Removes max-width from the Select component
- Enables full fluidity of TextInputBase components, according to the parent div's width
=> [DS-348]: feat: align all textfield based components with ds width rules

.github/workflows/combine-prs.yml
This PR introduces the [reusable workflow from orfium github actions](https://github.com/Orfium/orfium-github-actions#fe-combine-dependabot-prs) for combining dependabot PRs.
=> [NO-JIRA] Chore/reusable workflow from orfium github actions

src/components/Select/Select.tsx
[DS-367](https://orfium.atlassian.net/browse/DS-367)
Add optional onClear prop to Select component
=> [DS-367] feat: add onClear prop to Select

src/components/Switch/Switch.style.tsx, src/components/Switch/__snapshots__/Switch.stories.storyshot
- Change the label's font-size to 15 from 14
=> [NO-JIRA]: style: apply style fixes for dqa

src/components/TopAppBar/TopAppBar.stories.mdx, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot
This PR fix the documentation of the TopNavBar to show it correctly and use a correct version of the usecase
=> docs(topNavBar): update documentation of storybook

src/components/Filter/types.ts, src/components/Icon/index.ts, src/components/List/List.stories.mdx, src/components/List/ListItem/ListItem.style.ts, src/components/List/__snapshots__/List.stories.storyshot, src/components/List/utils.tsx, src/components/Select/Select.tsx
In this PR I added support for icons in the options of the list, and select items.
I added the support of `iconProps` where we directly use the props of the icon to define everything we want on the component. This way we have the flexibility of changing the list in anything we want
only snapshots
=> feat(list): add support for icons

.github/workflows/teardown-review-app.yml
Replace teardown workflow with reusable one from orfium-github-actions
=> Add reusable workflow for teardown

.github/workflows/teardown-review-app.yml
Fix access token to allow deletion of environments. Also, allow manual triggering of workflow
=> Allow manual triggering of teardown workflow

.github/workflows/sonar.yml, README.md, package.json, sonar-project.properties
After investigating our sonarqube on ictinus I found out that we don't have the coverage passed to it. This PR fix that and I replaced the `push` with `pull_request` as a suggestion to run in every PR.
We expect to have 85% coverage after merging this to the master.
=>  sonar workflow running correctly

src/components/Slider/Slider.tsx, src/index.tsx
- Fixes the default export of the Slider component
- Fixes an issue where changing the TextFields didn't call the onFinalChange callback
=> fix: fix slider export and onchange method issue

src/components/CheckBox/CheckBox.style.ts, src/components/CheckBox/CheckBox.tsx, src/components/CheckBox/__snapshots__/CheckBox.stories.storyshot, src/components/Icon/assets/checkmark.svg, src/components/Table/__snapshots__/Table.stories.storyshot
- Reverts changes caused by last PR
=> [NO-JIRA]: fix: revert v5 checkbox changes

src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot
[NDS-345](https://orfium.atlassian.net/browse/NDS-345)
=> [NDS-345] feat: disable autocomplete for Select

.eslintrc.json, src/components/DatePicker/Day/Day.style.ts, src/components/DatePicker/Day/Day.test.tsx, src/components/DatePicker/Day/Day.tsx, src/components/DatePicker/Month/Month.tsx, src/components/Notification/Banner/Banner.tsx, src/components/Notification/InlineNotification/InlineNotification.tsx, src/components/Notification/Notification.stories.mdx, src/components/Notification/Notification.test.tsx, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx, src/components/Pagination/Pagination.stories.mdx, src/components/Pagination/Pagination.tsx, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/Table/Table.stories.mdx, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Table/TableRowContext.ts, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.style.ts, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx, src/components/Table/components/TableCell/TableCell.tsx, src/components/Table/components/TableRow/TableRow.tsx, src/components/Table/components/TableRowWrapper/TableRowWrapper.tsx, src/components/TruncatedContent/TruncatedContent.stories.mdx, src/theme/palette.ts
**FOR V5**
Should be reviewed and merged after this https://github.com/Orfium/orfium-ictinus/pull/509 is merged
This PR is part of a chain of PRs to follow regarding props globalization.
ticket: https://orfium.atlassian.net/browse/NDS-338
Just updated snapshots where needed.
=> [NDS-338] Feat/Props Standardization (Booleans pt2)

src/components/Chart/BarChart/components/CustomTooltip/CustomTooltip.tsx, src/components/CheckBox/CheckBox.tsx, src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/OverlayComponent/OverlayComponent.tsx, src/components/DatePicker/OverlayComponent/components/MonthWrapper/MonthWrapper.tsx, src/components/Drawer/Drawer.style.ts, src/components/Drawer/Drawer.tsx, src/components/Drawer/Navigation/MenuItem/MenuItem.tsx, src/components/Drawer/Navigation/Navigation.tsx, src/components/ExpandCollapse/ExpandCollapse.tsx, src/components/ExpandCollapse/ExpandCollapse.types.ts, src/components/ExpandCollapse/utils.ts, src/components/Filter/Filter.style.ts, src/components/Filter/Filter.tsx, src/components/Filter/components/FilterBase/FilterBase.tsx, src/components/Filter/components/Options/Options.tsx, src/components/Filter/components/SearchInput/SearchInput.tsx, src/components/Filter/types.ts, src/components/Filter/utils.ts, src/components/IconButton/IconButton.tsx, src/components/Modal/Modal.tsx, src/components/Modal/ModalContent/ModalContent.tsx, src/components/Notification/NotificationVisual/NotificationVisual.tsx, src/components/Notification/Snackbar/Snackbar.tsx, src/components/Pagination/Pagination.tsx, src/components/SearchField/SearchFieldShowcase.tsx, src/components/Select/components/SelectMenu/SelectMenu.style.tsx, src/components/Select/components/SelectMenu/SelectMenu.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx, src/components/TopAppBar/components/Search/Search.style.ts
To be merged after [this](https://github.com/Orfium/orfium-ictinus/pull/520)
**FOR V5**
This PR is part of a chain of PRs to follow regarding props globalization.
ticket: https://orfium.atlassian.net/browse/NDS-338
Everything will be updated on a PR later. It's too much to keep track right now.
=> [NDS-338] Feat/Props Standardization (Booleans pt4) 

src/components/Radio/Radio.stories.mdx, src/components/Radio/Radio.test.tsx, src/components/SearchField/SearchField.stories.mdx, src/components/SearchField/SearchFieldShowcase.tsx, src/components/Select/Select.stories.mdx, src/components/Table/components/RenderRowOrNestedRow/RenderRowOrNestedRow.tsx, src/components/Table/components/RenderRowOrNestedRow/components/ExpandedButtonCell/ExpandedButtonCell.tsx, src/components/TextField/TextField.tsx, src/components/TopAppBar/TopAppBar.test.tsx, src/components/storyUtils/RadioButtonsShowcase/RadioButtonsShowcase.tsx, src/hooks/useToggle.ts
To be merged after [this](https://github.com/Orfium/orfium-ictinus/pull/522)
**FOR V5**
This PR is the last PR of a chain of PRs to regarding boolean props globalization.
ticket: https://orfium.atlassian.net/browse/NDS-338
Fixing what ever tests are breaking on this . Snapshots aren't supposed to be updated.
=> [NDS-338] Feat/Props Standardization (Booleans pt6) 

.storybook/preview.tsx, src/components/Overlay/Overlay.test.tsx, src/components/Switch/Switch.test.tsx, src/components/Tooltip/__snapshots__/Tooltip.stories.storyshot, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
Resolves breaking tests in : https://github.com/Orfium/orfium-ictinus/pull/527
More context: https://github.com/Orfium/orfium-ictinus/pull/527#issuecomment-1231450057
=> [NDS-338] Refactor/ fix tests on boolean naming conventions change 

src/components/Overlay/Overlay.tsx, src/utils/common.ts
A TS error occurs when trying to use the Overlay component on project, regarding the DivProps type
=> fix(Overlay): ts error

docs/guides/GLOBAL_STATES.stories.mdx
=> fix: update documentation to trigger release

src/components/Slider/Slider.stories.mdx, src/components/Slider/Slider.tsx, src/components/storyUtils/SliderShowcase/SliderShowcase.tsx
Minor fix on `next` after merge with master.
Slider component had some issues on bool prop namings
=> fix(bool prop): merge leftovers

src/components/Drawer/Drawer.tsx, src/components/Modal/ModalContent/ModalContent.tsx, src/components/Notification/__snapshots__/Notification.stories.storyshot, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx
This PR adds a few data test ids requested by the QA team.
Ticket: [here](https://orfium.atlassian.net/browse/NDS-444)
Updated snaps where needed
=> [NDS-444] Feat/ Data test ids

src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/DatePicker.tsx
[Ticket](https://orfium.atlassian.net/browse/NDS-445)
=> [NDS-445]: add DD MMM YYYY as a format option on datepicker

.github/workflows/pr.yml
update pr.yml to run on every PR
=> chore: update pr.yml to run on every PR

src/components/Chart/Chart.stories.mdx, src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/utils.ts
This PR fix the comparison problems on chromatic
=> [NDS-503] chore: date picker with fixed dates for correct comparison

.github/workflows/pr.yml, .github/workflows/teardown-review-app.yml
In this PR we add a check if the pr contains the label dependencies, then we mustn't create a Review App and we shouldn't delete as well
tickets:
[orfium.atlassian.net/browse/FE-26](https://orfium.atlassian.net/browse/FE-26)
[orfium.atlassian.net/browse/DEVOPS-800](https://orfium.atlassian.net/browse/DEVOPS-800)
=> [FE-26] [DEVOPS-800] Feat/ Disable Dependabot Review Apps 

environments/review.env
Add missing file for review apps teardown.
=> [FE-26] Fix/ Review Apps env file

src/components/Chart/Chart.stories.mdx, src/components/DatePicker/DatePicker.stories.mdx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Menu/Menu.tsx
[NDS-528](https://orfium.atlassian.net/browse/NDS-528)
[NDS-528]: https://orfium.atlassian.net/browse/NDS-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: menu dropdown stopped working

.github/workflows/ci.yml, .github/workflows/pr.yml
This PR changes the node version used in workflows to 18.13
=> Fix: node version

src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/storyUtils/EdgeCasesSelectShowcase/EdgeCasesSelectShowcase.style.ts, src/components/storyUtils/EdgeCasesSelectShowcase/EdgeCasesSelectShowcase.tsx, src/components/utils/PositionInScreen/PositionInScreen.style.tsx, src/components/utils/PositionInScreen/PositionInScreen.tsx, src/components/utils/PositionInScreen/hooks.ts
[NDS-591](https://orfium.atlassian.net/browse/NDS-591)
Dynamically position the SelectMenu based on the available space around the parent (Select's Textfield).
Pair-programmed with @Christos-Zacharopoulos 
[NDS-591]: https://orfium.atlassian.net/browse/NDS-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-591 - Select]: dynamically positioned SelectMenu

src/components/Button/ButtonLoader/ButtonLoader.style.ts, src/components/Button/ButtonLoader/ButtonLoader.tsx, src/components/Button/__snapshots__/Button.stories.storyshot, src/components/ButtonBase/ButtonBase.tsx
[NDS-593](https://orfium.atlassian.net/browse/NDS-593)
- Simplify styles for ButtonLoader
- Fix UI discrepancies 
[NDS-593]: https://orfium.atlassian.net/browse/NDS-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-593] refactor button loader [v5]

yarn.lock
This PR was created by the Combine PRs action by combining the following PRs:
closes #574 chore(deps): bump http-cache-semantics from 4.1.0 to 4.1.1 dependabot/npm_and_yarn/http-cache-semantics-4.1.1
closes #555 chore(deps): bump qs from 6.5.2 to 6.5.3 dependabot/npm_and_yarn/qs-6.5.3
closes #554 chore(deps): bump decode-uri-component from 0.2.0 to 0.2.2 dependabot/npm_and_yarn/decode-uri-component-0.2.2
closes #541 chore(deps): bump deep-object-diff from 1.1.7 to 1.1.9 dependabot/npm_and_yarn/deep-object-diff-1.1.9
closes #540 chore(deps): bump loader-utils from 1.4.0 to 1.4.2 dependabot/npm_and_yarn/loader-utils-1.4.2
=> Combined PR

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/DatePicker/utils.ts, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/hooks/useMultiselectUtils.ts, src/components/utils/PositionInScreen/hooks.ts
[NDS-626](https://orfium.atlassian.net/browse/NDS-626)
[NDS-626]: https://orfium.atlassian.net/browse/NDS-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-626 - Select] keep SelectMenu open when toggling options [v4.5]

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/components/SelectMenu/SelectMenu.tsx, src/components/Select/constants.ts, src/components/Select/hooks/useMultiselectUtils.ts
[NDS-628](https://orfium.atlassian.net/browse/NDS-628)
[NDS-628]: https://orfium.atlassian.net/browse/NDS-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-628] multiselect select all option [v4.5]

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Label/Label.style.ts, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.style.ts, src/components/TextInputBase/config.ts
This PR changes the SM variant of our text input. This affects input where we use it. The components that are affected by this are the following:
* input
* select
* datepicket
OLD
NEW
* Snapshots
=> [NDS-614][NDS-615]fix(inputBase): change height, label, text of SM variant

src/components/utils/PositionInScreen/hooks.ts, src/components/utils/PositionInScreen/utils.ts
[NDS-659](https://orfium.atlassian.net/browse/NDS-659)
[NDS-659]: https://orfium.atlassian.net/browse/NDS-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-659] fix: select resize observer loop limit exceeded [v4.5]

src/components/Filter/Filter.style.ts, src/components/Filter/Filter.test.tsx, src/components/Filter/Filter.tsx, src/components/storyUtils/FilterShowcase/MultiFilterShowcase.tsx, src/components/utils/PositionInScreen/PositionInScreen.style.tsx, src/components/utils/PositionInScreen/PositionInScreen.tsx
[NDS-680](https://orfium.atlassian.net/browse/NDS-680)
In this PR the required functionality for the Filter's Dropdown Options is added so it can be positioned dynamically on the screen based on the available window width and height.
[NDS-680]: https://orfium.atlassian.net/browse/NDS-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-680] feat: filter positioning [v4.5]

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/Select/hooks/useMultiselectUtils.ts, src/components/storyUtils/SelectShowcase/MultiSelectShowcase.tsx
[NDS-683](https://orfium.atlassian.net/browse/NDS-683)
Add the functionality to create tags when no options are available after searching.
[NDS-683]: https://orfium.atlassian.net/browse/NDS-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-683] feat: select and multiselect creatable options [v4.5]

src/components/Filter/Filter.stories.mdx, src/components/Filter/Filter.test.tsx, src/components/Filter/Filter.tsx, src/components/Filter/components/MultiFilter/MultiFilter.tsx, src/components/Filter/types.ts, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.stories.storyshot, src/components/storyUtils/FilterShowcase/MultiFilterShowcase.tsx, src/components/storyUtils/SelectShowcase/MultiSelectShowcase.tsx
[NDS-677](https://orfium.atlassian.net/browse/NDS-677)
[NDS-677]: https://orfium.atlassian.net/browse/NDS-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-677] feat: select all optional prop [v4.5]

docs/guides/DEVELOPMENT.stories.mdx, package.json, yarn.lock
- Adds a section in DS's documentation that details the steps needed in order to develop the package using `yalc`
=> [NDS-685]: docs: adds a .yalc section in the docs for active package development

src/components/Radio/Radio.style.ts
- Aligns the Radio button styles with the designs
=> [NDS-682]: fix: changes colors in radio button to reflect the designs

src/components/MultiTextFieldBase/MultiTextFieldBase.tsx, src/components/TextField/TextField.stories.mdx, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextField/hooks/useMultiTextFieldUtils.ts, src/components/TextInputBase/TextInputBase.style.ts, src/components/storyUtils/TextFieldShowcase/TextFieldShowcase.tsx
* minor CSS fix
* correctly update multi TextField selected values 
This PR introduces a new Prop to handle multiple values named `multiValuesHandler`. This `multiValuesHandler` by default is being passed the value but based on user needs it will change this to whatever handling a user might want. 
In the case of the showcase provided, we change a paste of text like `text1, text2` to multiple values on `enter`
Also it fixes the `sx` issue for multiValue case
=> multi TextField suggestions

src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Filter/components/MultiFilter/MultiFilter.tsx, src/components/MultiTextFieldBase/MultiTextFieldBase.tsx, src/components/MultiTextFieldBase/hooks.tsx, src/components/SearchField/__snapshots__/SearchField.stories.storyshot, src/components/Select/Select.stories.mdx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/TextArea/__snapshots__/TextArea.stories.storyshot, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.stories.storyshot, src/components/TextInputBase/TextInputBase.style.ts, src/components/TextInputBase/TextInputBase.tsx, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/storyUtils/PaletteShowcase/__snapshots__/PaletteShowcase.test.tsx.snap, src/components/storyUtils/SelectShowcase/MultiSelectShowcase.tsx
[NDS-686](https://orfium.atlassian.net/browse/NDS-686)
[NDS-686]: https://orfium.atlassian.net/browse/NDS-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-686] multi components DQA [v4.5]

src/components/ThemeProvider/ThemeProvider.style.ts, src/components/ThemeProvider/ThemeProvider.tsx
[NDS-157](https://orfium.atlassian.net/browse/NDS-157)
[NDS-157]: https://orfium.atlassian.net/browse/NDS-157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-157] feat: custom scrollbar [v4.5]

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/TextField/TextField.stories.mdx, src/components/TextField/__snapshots__/TextField.stories.storyshot
This PR fixes all compatibility issues to have all stories accepted as the baseline
=> fix: minor ui fixes for compatibility with figma

package.json, yarn.lock
Moves `@emotion` deps to dev and peer dependencies. Fixes toolbox issues . Should fix all issues where there is a clash between ictinus and project-specific instances of emotion.
Blocking for https://github.com/Orfium/toolbox/pull/52
=> fix: dependencies

src/components/Button/__snapshots__/Button.stories.storyshot, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/IconButton/__snapshots__/IconButton.stories.storyshot, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/Overlay/__snapshots__/Overlay.stories.storyshot, src/components/Pagination/__snapshots__/Pagination.stories.storyshot, src/components/Table/__snapshots__/Table.stories.storyshot, src/theme/states/hover.ts, src/theme/states/pressed.ts
[NDS-712](https://orfium.atlassian.net/browse/NDS-712)
[NDS-712]: https://orfium.atlassian.net/browse/NDS-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-712] fix: hover for transparent buttons [v4.5]

.github/workflows/main.yml, src/components/Avatar/Avatar.stories.mdx
Updating main.yml based on https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet to get all branches
=> chore: change to double asterisk

src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Tooltip/Tooltip.stories.mdx, src/components/Tooltip/Tooltip.style.ts, src/components/Tooltip/Tooltip.tsx, src/components/storyUtils/TooltipShowcase/TooltipShowcase.tsx
[NDS-741](https://orfium.atlassian.net/browse/NDS-741)
[NDS-741]: https://orfium.atlassian.net/browse/NDS-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-741] fix: tooltip border radius [v4.5]

src/components/Filter/Filter.tsx, src/components/Filter/components/MultiFilter/MultiFilter.tsx, src/components/Filter/components/Options/Options.tsx
[NDS-744](https://orfium.atlassian.net/browse/NDS-744)
[NDS-744]: https://orfium.atlassian.net/browse/NDS-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-744] fix: filter search default value [v5]

src/components/Filter/Filter.tsx, src/components/Filter/components/MultiFilter/MultiFilter.tsx, src/components/Filter/components/Options/Options.tsx
[NDS-744](https://orfium.atlassian.net/browse/NDS-744)
[NDS-744]: https://orfium.atlassian.net/browse/NDS-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-744] fix: filter search default value [v4]

src/components/TextArea/TextArea.tsx
[NDS-746](https://orfium.atlassian.net/browse/NDS-746)
[NDS-746]: https://orfium.atlassian.net/browse/NDS-746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-746] fix: textarea cols and rows [v4.5]

src/components/Filter/Filter.tsx
[NDS-763](https://orfium.atlassian.net/browse/NDS-763)
[NDS-763]: https://orfium.atlassian.net/browse/NDS-763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-763] fix: filter initial value not shown in label [v4]

src/components/Table/components/ExtendedColumnItem/ExtendedColumnItem.tsx, src/components/Table/utils/utils.ts
[NDS-757](https://orfium.atlassian.net/browse/NDS-757)
[NDS-757]: https://orfium.atlassian.net/browse/NDS-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-757] fix: table sortable headers ui issue [v4.5]

src/components/Table/components/ExtendedColumnItem/ExtendedColumnItem.tsx, src/components/Table/utils/utils.ts
[NDS-757](https://orfium.atlassian.net/browse/NDS-757)
[NDS-757]: https://orfium.atlassian.net/browse/NDS-757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-757] fix: table sortable headers ui issue [v5]

.storybook/preview.tsx, src/components/Chart/Chart.stories.mdx
[NDS-784](https://orfium.atlassian.net/browse/NDS-784)
[NDS-784]: https://orfium.atlassian.net/browse/NDS-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-784] feat: add delay to chromatic screenshots [v5]

.github/workflows/main.yml, environments/common.env
This PR fix the deployment of ictinus with the new restriction of semantic-release
=> fix: deployment node to LTS

src/components/DatePicker/DatePicker.test.tsx, src/components/DatePicker/Day/Day.tsx, src/components/DatePicker/Day/__snapshots__/Day.test.tsx.snap, src/components/DatePicker/Month/Month.tsx, src/components/DatePicker/Month/Month.utils.ts, src/components/DatePicker/Month/__snapshots__/Month.test.tsx.snap, src/components/DatePicker/OverlayComponent/OverlayComponent.tsx, src/components/DatePicker/OverlayComponent/__snapshots__/OverlayComponent.test.tsx.snap, src/components/DatePicker/OverlayComponent/components/MonthWrapper/MonthWrapper.test.tsx, src/components/DatePicker/OverlayComponent/components/MonthWrapper/MonthWrapper.tsx, src/components/DatePicker/OverlayComponent/components/MonthWrapper/__snapshots__/MonthWrapper.test.tsx.snap, src/components/DatePicker/OverlayComponent/utils.ts, src/components/DatePicker/utils.ts
[NDS-799](https://orfium.atlassian.net/browse/NDS-799)
[NDS-805](https://orfium.atlassian.net/browse/NDS-805)
In this PR:
- issue [NDS-799](https://orfium.atlassian.net/browse/NDS-799) is resolved: some days for some months were not rendered because of false calculation of weeks per month.
- issue [NDS-805](https://orfium.atlassian.net/browse/NDS-805) is resolved: when initial values are provided the calendar renders the current month only
- some tests were added to increase coverage
- test-ids were added
[NDS-799]: https://orfium.atlassian.net/browse/NDS-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NDS-805]: https://orfium.atlassian.net/browse/NDS-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> [NDS-799] fix: date picker calendar days hidden [v5]

.github/workflows/teardown.yml
Update teardown with concurrency.
=> fix: update teardown

src/index.tsx
Export useTypeColorToColorMatch hook.
=> fix: export useTypeColorToColorMatch hook

src/index.tsx
Small chore fix for exported hook useTypeColorToColorMatch
=> chore: update export useTypeColorToColorMatch

src/components/Filter/Filter.tsx
[NDS-864](https://orfium.atlassian.net/browse/NDS-864)
[NDS-864]: https://orfium.atlassian.net/browse/NDS-864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-864] fix: filter label doesnt update externally

src/components/Menu/Menu.style.ts, src/components/Menu/Menu.tsx, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/TopAppBar/TopAppBar.test.tsx, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/utils/DropdownOptions/index.tsx
[NDS-682](https://orfium.atlassian.net/browse/NDS-862)
In this PR:
- the max-width of menu list is fixed.
- positioning is fixed with the usage of `PositionInScreen` component in order to position the menu list correctly when the Menu Button is placed on the edges of the window
[NDS-682]: https://orfium.atlassian.net/browse/NDS-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-682] fix: menu max-width and positioning

src/components/TextArea/TextArea.style.ts, src/components/TextArea/__snapshots__/TextArea.stories.storyshot
[NDS-863](https://orfium.atlassian.net/browse/NDS-863)
[NDS-863]: https://orfium.atlassian.net/browse/NDS-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-863] fix: textarea auto sizing

src/components/utils/ClickAwayListener/ClickAwayListener.tsx
This PR adds the event on clickAwayListner click
=> feat: adding event clickawaylistener

src/__storyshots__/Original Components/Notification-InlineNotificationStory.snap, src/components/ButtonBase/ButtonBase.tsx, src/components/Filter/Filter.test.tsx
this PR spreads rest of the props to button so we can pass aria labels etc to the wrapper
=> feat(ButtonBase): spread rest of props to button

src/components/Table/Table.stories.mdx, src/components/Table/Table.tsx, src/components/Table/utils/TableStoryComponents.tsx
This PR adds the Cell and Row types on Table documentation to showcase how it can be used
N/A
=> [NDS-891] docs(table): add table, table cell and table row props

src/__storyshots__/Original Components/TopNavBar-Playground.snap, src/__storyshots__/Original Components/TopNavBar-WithAdditionalTools.snap, src/__storyshots__/Original Components/TopNavBar-WithDarkThemeEnabled.snap, src/__storyshots__/Original Components/TopNavBar-WithLogoPlaceholder.snap, src/__storyshots__/Updated Components/Menu-MenuComponents.snap, src/__storyshots__/Updated Components/Menu-MenuDisabledKeys.snap, src/__storyshots__/Updated Components/Menu-MenuItemDividerStory.snap, src/__storyshots__/Updated Components/Menu-MenuTriggers.snap, src/__storyshots__/Updated Components/Progress Indicator-BlockProgressIndicator.snap, src/__storyshots__/Updated Components/Progress Indicator-CircularProgressIndicatorErrorStates.snap, src/__storyshots__/Updated Components/Progress Indicator-CircularProgressIndicatorIndeterminate.snap, src/__storyshots__/Updated Components/Progress Indicator-CircularProgressIndicatorWithPercentage.snap, src/__storyshots__/Updated Components/Progress Indicator-LinearProgressIndicatorIndeterminate.snap, src/__storyshots__/Updated Components/Progress Indicator-LinearProgressIndicatorWithPercentage.snap, src/__storyshots__/Updated Components/Progress Indicator-Playground.snap, src/components/Menu/Menu.mdx, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.style.ts, src/components/Menu/Menu.tokens.ts, src/components/Menu/Menu.tsx, src/components/Menu/MenuItemDivider.tsx, src/components/TopAppBar/TopAppBar.tsx, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/TopAppBar/components/UserMenu/UserMenu.tsx, src/components/Typography/Typography.tsx
This PR introduce the new menu component and replace the old from topbar
[Ticket](https://www.figma.com/file/8kMPBNYHHXz2AtkzeeDmk5/DS-%7C-V5-%5BWIP%5D?type=design&node-id=23277-132174&mode=design&t=IcWAchvI7iM86IBc-0)
=> [NDS-861] feat(Menu): new menu component

src/components/Modal/Modal.style.ts
This PR changes the modal background to the global use of black 0.75 opacity.
=> [NDS-893] style(modal): fix background of modal

src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/DatePicker.types.ts, src/components/Filter/Filter.tokens.ts, src/components/Filter/Filter.tsx, src/components/Filter/Filter.types.ts, src/components/Filter/components/FilterButton/FilterButton.style.ts, src/components/Filter/components/FilterButton/FilterButton.tsx, src/components/Filter/components/FilterButton/index.ts, src/components/Filter/components/FilterMenu/FilterMenu.style.ts, src/components/Filter/components/FilterMenu/FilterMenu.tsx, src/components/Filter/components/FilterMenu/components/FilterSearchField/FilterSearchField.style.ts, src/components/Filter/components/FilterMenu/components/FilterSearchField/FilterSearchField.tsx, src/components/Filter/components/FilterMenu/components/FilterSearchField/index.ts, src/components/Filter/components/FilterMenu/components/Options/Options.style.ts, src/components/Filter/components/FilterMenu/components/Options/Options.tsx, src/components/Filter/components/FilterMenu/components/Options/index.ts, src/components/Filter/components/FilterMenu/index.ts, src/components/Filter/constants.ts, src/components/Filter/hooks/index.ts, src/components/Filter/hooks/useFilterWithSelectionUtils.ts, src/components/Filter/index.ts, src/components/Menu/Menu.tsx, src/components/MultiTextFieldBase/MultiTextFieldBase.style.ts, src/components/MultiTextFieldBase/MultiTextFieldBase.tsx, src/components/utils/PositionInScreen/hooks.ts, src/theme/tokens/components/variables/filter.ts
[NDS-887](https://orfium.atlassian.net/browse/NDS-887)
[NDS-887]: https://orfium.atlassian.net/browse/NDS-887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-887] feat(Filter): implementation [part 2]

src/components/Notification/Banner/Banner.tsx, src/components/Notification/Notification.stories.mdx, src/components/Notification/subcomponents/CompactNotification/CompactNotification.style.ts, src/components/Notification/subcomponents/CompactNotification/CompactNotification.tsx
[Ticket](https://orfium.atlassian.net/browse/NDS-901)
=> feat(banner): add alternative cta / button

.github/workflows/main.yml, .releaserc, environments/v4.env
=> feat: adding v4 to environments for parallel deployment

package.json, src/__storyshots__/Original Components/Navigation-NavigationStory.snap, src/__storyshots__/Original Components/Navigation-NavigationWithCustomComponent.snap, src/components/Breadcrumb/Breadcrumb.stories.tsx, src/components/Navigation/Directory/MenuItem/MenuItem.tsx, src/components/Navigation/types.ts, src/components/storyUtils/BreadcrumbShowcase/BreadcrumbShowcase.tsx, src/components/storyUtils/NavigationShowcase/NavigationShowcase.tsx, src/hooks/storyUtils/DemoUseSearchQueryParams.tsx, yarn.lock
=> feat: upgrade react-router to v6

src/components/Table/Table.mdx, src/components/Table/Table.tsx, src/components/Table/utils/TableStoryComponents.tsx
This PR adds more types missed by storybook and adding more description for others
N/A
=> docs(table): adding all small types storybook missed

.storybook/preview-head.html, docs/Foundations/DesignTokens/Semantic/TYPOGRAPHY.mdx, docs/Foundations/Layout/BREAKPOINTS.mdx, docs/Foundations/THEME.mdx, docs/Utilities/THEME_UTILITIES.mdx, src/components/Select/Select.stories.tsx
[NDS-959](https://orfium.atlassian.net/browse/NDS-959)
[NDS-959]: https://orfium.atlassian.net/browse/NDS-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-959] fix: storybook table styles

docs/Foundations/DesignTokens/Dimension/BORDER_RADIUS.mdx, docs/Foundations/DesignTokens/Dimension/BORDER_WIDTH.mdx, docs/Foundations/DesignTokens/Dimension/MIN_HEIGHT.mdx, docs/Foundations/DesignTokens/Dimension/OPACITY.mdx, docs/Foundations/DesignTokens/Dimension/SIZING.mdx, docs/Foundations/DesignTokens/Dimension/SPACING.mdx, docs/Foundations/DesignTokens/Dimension/STATE.mdx, docs/Foundations/DesignTokens/Global/BORDER_RADIUS.mdx, docs/Foundations/DesignTokens/TOKENS_ABOUT.mdx, docs/Foundations/THEME.mdx, docs/Utilities/THEME_UTILITIES.mdx, src/storybook/Showcases/BorderWidthShowcase/BorderWidthShowcase.tsx, src/storybook/Showcases/BorderWidthShowcase/index.ts, src/storybook/Showcases/MinHeightShowcase/MinHeightShowcase.tsx, src/storybook/Showcases/MinHeightShowcase/index.ts, src/storybook/Showcases/OpacityShowcase/OpacityShowcase.tsx, src/storybook/Showcases/OpacityShowcase/index.ts, src/storybook/Showcases/SizingShowcase/SizingShowcase.tsx, src/storybook/Showcases/SpacingSizingShowcase/SpacingSizingShowcase.tsx, src/storybook/Showcases/StateShowcase/StateShowcase.tsx, src/storybook/Showcases/StateShowcase/index.ts, src/theme/utils.ts
[NDS-989](https://orfium.atlassian.net/browse/NDS-989)
Part 3:
- Update Storybook Documentation with Showcases
[NDS-989]: https://orfium.atlassian.net/browse/NDS-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-989] feat: get latest tokens [Part 3]

src/components/DatePicker/DatePicker.test.tsx, src/components/DatePicker/__snapshots__/DatePicker.stories.storyshot, src/components/Filter/Filter.tsx, src/components/Menu/__snapshots__/Menu.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.stories.storyshot, src/components/TopAppBar/__snapshots__/TopAppBar.test.tsx.snap, src/components/utils/PositionInScreen/PositionInScreen.style.tsx, src/components/utils/PositionInScreen/PositionInScreen.tsx, src/components/utils/PositionInScreen/hooks.ts
Resolves [NDS-881]
The issue was that initial dimension/coords calculations were wrong because the DOM elements did not exist in the document. So while `useLayoutEffect` corrected the flickering issue, it still could not fix the 1st time the list appeared in the document. 
The chosen solution was to keep the list elements always inside the document but hidden, so that the 1st time a dimension/coord calculation happens it can yield correct results.
Another change made was that the DOM element refs are now kept in state, since they were used as dependency arrays to hooks. 
[NDS-881]: https://orfium.atlassian.net/browse/NDS-881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: resolve positioning issues in Select and Filter

src/__storyshots__/Updated Components/Table/Table-ColumnChooser.snap, src/__storyshots__/Updated Components/Table/Table-ColumnGroups.snap, src/components/Table/Table.mdx, src/components/Table/Table.stories.tsx, src/components/Table/Table.style.ts, src/components/Table/Table.tsx, src/components/Table/components/TD/TD.style.ts, src/components/Table/components/TTitle/TTitle.style.ts, src/components/Table/components/TTitle/TTitle.tsx, src/components/Table/components/TTitle/components/ColumnChooser/ColumnChooser.style.ts, src/components/Table/components/TTitle/components/ColumnChooser/ColumnChooser.tsx, src/components/Table/components/TTitle/components/ColumnChooser/index.ts, src/components/Table/components/TTitle/components/utils.ts, src/components/Table/constants.tsx, src/components/Table/hooks/useTable.tsx, src/components/Table/types.ts, src/components/Table/utils/TableStoryComponents.tsx
[NDS-987](https://orfium.atlassian.net/browse/NDS-987)
[NDS-987]: https://orfium.atlassian.net/browse/NDS-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-987] feat: table title and column chooser

src/components/Table/__snapshots__/Table.stories.storyshot, src/components/Table/components/RenderRowOrNestedRow/components/ContentCell/ContentCell.tsx
=> fix: data-column value that was missed in previous patch

src/components/Filter/Filter.tsx, src/components/Filter/utils.ts
[NDS-1002](https://orfium.atlassian.net/browse/NDS-1002)
[NDS-1002]: https://orfium.atlassian.net/browse/NDS-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-1002] fix: multi filter initial value not displayed

.storybook/preview.tsx, src/__storyshots__/Updated Components/Table/Table-ColumnChooser.snap, src/__storyshots__/Updated Components/Table/Table-RowSelection.snap, src/__storyshots__/Updated Components/Table/Table-Sorting.snap, src/components/Table/Table.mdx, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/components/TD/TD.style.ts, src/components/Table/components/TD/TD.tsx, src/components/Table/components/TH/TH.style.ts, src/components/Table/components/TH/TH.tsx, src/components/Table/components/TR/TR.style.ts, src/components/Table/components/TR/TR.tsx, src/components/Table/components/TTitle/TTitle.style.ts, src/components/Table/components/TTitle/TTitle.tsx, src/components/Table/components/TTitle/components/ColumnChooser/ColumnChooser.tsx, src/components/Table/hooks/useTable.tsx, src/components/Table/types.ts, src/components/Table/utils/TableStoryComponents.tsx
[NDS-992](https://orfium.atlassian.net/browse/NDS-992)
Introduce row selection with title actions:
- Row Selection state.
- Default action and bulk actions for rows, displayed on the title.
[NDS-992]: https://orfium.atlassian.net/browse/NDS-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-992] feat: table row selection and title actions

src/__storyshots__/Updated Components/Table/Table-RowDetails.snap, src/components/Table/Table.mdx, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/components/TD/TD.style.ts, src/components/Table/components/TD/TD.tsx, src/components/Table/components/TH/TH.style.ts, src/components/Table/components/TH/TH.tsx, src/components/Table/components/TR/TR.style.ts, src/components/Table/components/TR/TR.tsx, src/components/Table/constants.tsx, src/components/Table/hooks/useTable.tsx, src/components/Table/types.ts, src/components/Table/utils/TableStoryComponents.tsx
[NDS-993](https://orfium.atlassian.net/browse/NDS-993)
[NDS-993]: https://orfium.atlassian.net/browse/NDS-993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NDS-993] feat: table expandable row

.husky/pre-commit, package.json, src/__storyshots__/Updated Components/Fields/Select-MultiSelect.snap, src/__storyshots__/Updated Components/Menu-MenuTriggers.snap, src/__storyshots__/Updated Components/Menu-MenuWithCustomListWidthAndHeight.snap, src/__storyshots__/Updated Components/Progress Indicator-BlockProgressIndicator.snap, src/__storyshots__/Updated Components/Progress Indicator-CircularProgressIndicatorErrorStates.snap, src/__storyshots__/Updated Components/Progress Indicator-CircularProgressIndicatorIndeterminate.snap, src/__storyshots__/Updated Components/Progress Indicator-CircularProgressIndicatorWithPercentage.snap, src/__storyshots__/Updated Components/Progress Indicator-LinearProgressIndicatorIndeterminate.snap, src/__storyshots__/Updated Components/Progress Indicator-LinearProgressIndicatorWithPercentage.snap, src/__storyshots__/Updated Components/Progress Indicator-Playground.snap, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.style.ts, src/components/Menu/Menu.tsx, src/components/MultiTextFieldBase/hooks.tsx, tsconfig.json, yarn.lock
[Ticket](https://orfium.atlassian.net/browse/SYN-1690)
=> [SYN-1690] fix: add custom width and height on menu list component

sonar-project.properties
This PR updates the sonar-project.properties to use the new SonarCloud organization and projectKey.
=> ci: update sonar-project.properties for sonar cloud

.github/workflows/main.yml, sonar-project.properties
- Fix deployments permission
- Fix sonar organization
=> fix: deployments in v4

src/components/DatePicker/DatePicker.test.tsx, src/components/DatePicker/DatePicker.tsx
[Ticket](https://orfium.atlassian.net/browse/CDP-369)
=> Datepicker fix date range

src/components/Chart/LineChart/utils.ts, src/components/Filter/Filter.tsx, src/components/Filter/hooks/useMultiFilterUtils.ts, src/components/List/NormalList/NormalList.tsx, src/components/MultiTextFieldBase/MultiTextFieldBase.tsx, src/components/ThemeProvider/ThemeProvider.tsx, src/components/storyUtils/BreadcrumbShowcase/BreadcrumbShowcase.tsx, src/components/storyUtils/ColorUtility/ColorUtility.tsx
This PR takes care of importing without tree shake the whole lodash
=> refactor: update lodash imports to named imports for consistency

.gitignore, src/__storyshots__/Updated Components/Search-CustomSearch.snap, src/__storyshots__/Updated Components/Search-FilteredSearch.snap, src/components/Box/Box.tsx, src/components/Box/Box.types.ts, src/components/Box/Box.utilities.ts, src/components/Search/Search.stories.tsx, src/components/Search/Search.style.ts, src/components/Search/Search.tsx, src/components/Search/Search.types.ts
This PR implements custom (advanced) search capabilities by passing children to the filter. This being implemented currently on Filter.
https://www.figma.com/design/3bbbVrR8SymH76R7iYYHU6/Matching-App---Ictinus-V5?node-id=1048-94833&m=dev
=> [CDP-373] feat: implement CustomSearch component with filter options and update Search styles

src/components/Drawer/Drawer.style.ts, src/components/Modal/Modal.style.ts
[CDP-411](https://orfium.atlassian.net/browse/CDP-411)
[CDP-411]: https://orfium.atlassian.net/browse/CDP-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDP-411] feat: change background color of modal and drawer

src/__storyshots__/Updated Components/Tabs/TabStepper-Playground.snap, src/__storyshots__/Updated Components/Tabs/TabStepper-TabStepperOrientation.snap, src/__storyshots__/Updated Components/Tabs/TabStepper-TabStepperStatuses.snap, src/__storyshots__/Updated Components/Tabs/TabStepper-TabStepperWithContent.snap, src/__storyshots__/Updated Components/Tabs/Tabs-Playground.snap, src/__storyshots__/Updated Components/Tabs/Tabs-TabsOrientation.snap, src/__storyshots__/Updated Components/Tabs/Tabs-TabsWithContent.snap, src/__storyshots__/Updated Components/Tabs/Tabs-TabsWithCounter.snap, src/components/TabStepper/TabStepper.mdx, src/components/TabStepper/TabStepper.tsx, src/components/TabStepper/components/TabStep/TabStep.style.ts, src/components/TabStepper/components/TabStep/TabStep.tsx, src/components/TabStepper/types.ts, src/components/TabStepper/utils/TabStepperStoryComponents.tsx, src/components/Tabs/Tabs.mdx, src/components/Tabs/Tabs.tsx, src/components/Tabs/components/Tab/Tab.style.ts, src/components/Tabs/components/Tab/Tab.tsx, src/components/Tabs/components/TabPanel/TabPanel.tsx, src/components/Tabs/components/TabsContainer/TabsContainer.style.ts, src/components/Tabs/components/TabsContainer/TabsContainer.tsx, src/components/Tabs/types.ts, src/components/Tabs/utils/TabsStoryComponents.tsx
[CDP-416](https://orfium.atlassian.net/browse/CDP-416)
Add sx prop to:
- Tabs
- TabStepper
and drill down to all subcomponents
[CDP-416]: https://orfium.atlassian.net/browse/CDP-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDP-416] feat: add sx prop to Tabs and TabStepper

src/__storyshots__/Updated Components/Fields/DatePicker-DatePickerWithFilter.snap, src/__storyshots__/Updated Components/Filter-FilterWithDatePicker.snap, src/components/DatePicker/DatePickInput/DatePickInput.tsx, src/components/DatePicker/DatePicker.stories.tsx, src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/DatePicker.types.ts
[CDP-424](https://orfium.atlassian.net/browse/CDP-424)
[CDP-424]: https://orfium.atlassian.net/browse/CDP-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add onClear prop on "filtered" DatePicker

.eslintignore, src/__storyshots__/Updated Components/Notifications/Toast-Controlled.snap, src/__storyshots__/Updated Components/Notifications/Toast-Default.snap, src/__storyshots__/Updated Components/Notifications/Toast-Error.snap, src/__storyshots__/Updated Components/Notifications/Toast-Informational.snap, src/__storyshots__/Updated Components/Notifications/Toast-Neutral.snap, src/__storyshots__/Updated Components/Notifications/Toast-Playground.snap, src/__storyshots__/Updated Components/Notifications/Toast-ShouldCloseOnAction.snap, src/__storyshots__/Updated Components/Notifications/Toast-Success.snap, src/__storyshots__/Updated Components/Notifications/Toast-Warning.snap, src/__storyshots__/Updated Components/Notifications/Toast-WithButtons.snap, src/__storyshots__/Updated Components/Notifications/Toast-WithCustomIcon.snap, src/components/Notification/Notification.mdx, src/components/Notification/Notification.stories.tsx, src/components/Notification/Notification.test.tsx, src/components/ThemeProvider/ThemeProvider.style.ts, src/components/Toast/Toast.mdx, src/components/Toast/Toast.stories.tsx, src/components/Toast/Toast.style.ts, src/components/Toast/Toast.test.tsx, src/components/Toast/Toast.tsx, src/components/Toast/Toast.types.ts, src/components/Toast/index.ts, src/components/Toast/index.tsx, src/components/ToastV4/ToastV4.style.ts, src/components/ToastV4/ToastV4.test.tsx, src/components/ToastV4/ToastV4.tsx, src/components/ToastV4/index.tsx, src/index.ts, tsconfig.json
[CDP-408](https://orfium.atlassian.net/browse/CDP-408)
[CDP-408]: https://orfium.atlassian.net/browse/CDP-408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: toast v5

src/__storyshots__/Original Components/Modal-WithToast.snap, src/components/Modal/Modal.stories.tsx, src/components/Table/Table.tsx, src/components/Toast/Toast.style.ts, src/hooks/useOverlayStack.ts
- Fix toast z-index issue.
- Respect top layer (toasts) in overlay stack.
- Fix table row key issue.
=> fix: table row key and toast z-index

src/components/DatePicker/DatePicker.tsx
[CDP-462](https://orfium.atlassian.net/browse/CDP-462)
[CDP-462]: https://orfium.atlassian.net/browse/CDP-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CDP-462] feat(datepicker): clear preset option on input clear

src/components/Menu/Menu.tsx
=> feat: update menu children type

.changeset/polite-baths-look.md, .github/workflows/release.yml
Add permissions for changesets bot.
=> chore: add permissions

.changeset/yellow-swans-report.md, package.json, vite.config.ts
Make generated css file name explicit `styles.css`
=> fix: explicit generated css filename

apps/storybook/src/__storyshots__/Updated Components/Tooltip-TooltipPlacement.snap, apps/storybook/src/__storyshots__/Vanilla/Box-Default.snap, apps/storybook/src/__storyshots__/Vanilla/ThemeProvider-Default.snap, apps/storybook/src/storybook.test.tsx
Serialize semantic versioning strings in data attributes
=> fix: serialize sem versioning
